In [27]:
import pandas as pd

In [28]:
from src.indicateurs import (
    TVAIndicators,
    ImportExportIndicators,
    ComptabiliteIndicators,
    ControleIndicators,
    AdvancedIndicators,
)
from src.utils import INDICATEUR_LIST, INDICATEUR_LIST_DROPDOWN, df_columns_process

In [29]:
bd_tva_file ="./data/bd_tva_complete.csv"
benefices_complete_file = "./data/benefices_complete.csv"
contribuale_file = "./data/contribuables.csv"
dgd_file = "./data/dgd_complete.csv"
programmation_file = "./data/programmation_controles.csv"
merged_file = "./data/merged_data.csv"
dcf_tva_deduction_file = "./data/dcf_tva_deduction.csv"
total_insd_file ="./data/total_insd_v2.csv"

risk_file ='./data/ana_risk.csv'

In [38]:
risk_file ='./data/ana_risk.csv'
df_risk = pd.read_csv(risk_file)

In [30]:
df_merged = pd.read_csv(merged_file)
df_merged.head()

/tmp/ipykernel_19623/2145189752.py:1: DtypeWarning: Columns (8,17,20,68,69,70) have mixed types. Specify dtype option on import or set low_memory=False.
  df_merged = pd.read_csv(merged_file)

,ID_CONTR,NUM_IFU,NOM_x,NOM_MINEFID_x,DATE_CREATION,DATE_IMMAT_x,ETAT,TEL,EMAIL,CODE_FJ,...,ANNEE_FISCAL_y,CODE_ELT_LIQ,VALEUR_NUMERIQUE,TYPE_BENEFICE,DATE_IMMAT_y,NOM_MINEFID_y,DATE_DERNIERE_VG,DATE_DERNIERE_VP,DATE_DERNIERE_AVIS,DERNIERE_GESTION_SOUMIS_VERIF
0,455301,00000003T,MAROU LENGLENGUE,MAROU LENGLENGUE,2006-01-12,2006-01-13,ACTIF,70-11-29-77,NaN,43,...,NaN,NaN,NaN,NaN,2006-01-13 00:00:00,MAROU LENGLENGUE,NaN,NaN,NaN,NaN
1,455656,00000005J,MAHAMADI ZOUNGRANA,MAHAMADI ZOUNGRANA (ETS WEND KONTA (EWK)),2006-02-03,2006-02-03,ACTIF,50303511,NaN,43,...,NaN,NaN,NaN,NaN,2006-02-03 00:00:00,MAHAMADI ZOUNGRANA (ETS WEND KONTA (EWK)),NaN,NaN,NaN,NaN
2,455304,00000007Y,CLEMENT BASSONO,CLEMENT BASSONO (GENIE MULTI-SERVICES),2006-01-12,2006-01-13,ACTIF,70-23-96-06,NaN,43,...,NaN,NaN,NaN,NaN,2006-01-13 00:00:00,CLEMENT BASSONO (GENIE MULTI-SERVICES),NaN,NaN,NaN,NaN
3,455310,00000018K,LAMOUSSA HAMED GANEMTORE,LAMOUSSA HAMED GANEMTORE (UNIVERSE AFRICA TOWI...,2006-01-16,2006-01-16,ACTIF,50-37-19-15,NaN,43,...,NaN,NaN,NaN,NaN,2006-01-16 00:00:00,LAMOUSSA HAMED GANEMTORE (UNIVERSE AFRICA TOWI...,NaN,NaN,NaN,NaN
4,455374,00000019F,SYNOVIE SARL,SYNOVIE SARL,2006-01-16,2006-01-16,ACTIF,50/36/10/92,NIKIEMAD@HOTMAIL.COM,20,...,2019.0,70.0,77282000.0,IS,2006-01-16 00:00:00,SYNOVIE SARL,2022-12-08 00:00:00,NaN,2023-02-13 00:00:00,2023.0

In [31]:
df_input =df_merged[:20000].copy()
df_risk_2 = df_columns_process(df=df_input,columns_list=["NUM_IFU", "ANNEE"],duplicate_check_columns=["NUM_IFU", "ANNEE"],handle_duplicates="drop")

🔍 Doublons détectés: 19894 lignes avec des combinaisons dupliquées sur ['NUM_IFU', 'ANNEE']
📋 Exemples de combinaisons dupliquées:
   • NUM_IFU=00000019F + ANNEE=2017.0 (162 occurrences)
   • NUM_IFU=00000019F + ANNEE=2018.0 (162 occurrences)
   • NUM_IFU=00000019F + ANNEE=2019.0 (162 occurrences)
   • NUM_IFU=00000019F + ANNEE=2020.0 (162 occurrences)
   • NUM_IFU=00000019F + ANNEE=2021.0 (162 occurrences)
✅ Doublons supprimés. Lignes restantes: 240
📊 DataFrame final: 240 lignes, 2 colonnes

In [32]:
df_risk_2.duplicated(subset=["NUM_IFU", "ANNEE"]).value_counts()

False    240
Name: count, dtype: int64

In [33]:

df_result = TVAIndicators.calculate_indicator_1(df_input,risk_df=df_risk_2)
df_result  =TVAIndicators.calculate_indicator_2(df_input, risk_df=df_result)
df_result =TVAIndicators.calculate_indicator_12(df_input, risk_df=df_result)
df_result=TVAIndicators.calculate_indicator_8(df_input, risk_df=df_result)
df_result =TVAIndicators.calculate_indicator_14(df_input, risk_df=df_result)
df_result =TVAIndicators.calculate_indicator_13(df_input, risk_df=df_result)
df_result

/media/Data/DGI/project/ana_risk/src/indicateurs/tva_indicators.py:167: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '20117008.8' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  risk_df.loc[mask, "GAP_IND_1"] = result[0]
/media/Data/DGI/project/ana_risk/src/indicateurs/tva_indicators.py:482: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '29893.100000000002' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  risk_df.loc[mask, "GAP_IND_12"] = result[0]
/media/Data/DGI/project/ana_risk/src/indicateurs/tva_indicators.py:375: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '18859695.75' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  risk_df.loc[mask, "GAP_IND_8"] = result[0]
/media/Data/DGI/project/ana_risk/src/indicateurs/tva_indicators.py:612: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '9978264.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  risk_df.loc[mask, "GAP_IND_13"] = result[0]

,NUM_IFU,ANNEE,RISQUE_IND_1,GAP_IND_1,SCORE_IND_1,RISQUE_IND_2,GAP_IND_2,SCORE_IND_2,RISQUE_IND_12,GAP_IND_12,SCORE_IND_12,RISQUE_IND_8,GAP_IND_8,SCORE_IND_8,RISQUE_IND_14,RISQUE_IND_13,GAP_IND_13,SCORE_IND_13
0,00000003T,NaN,Non disponible,0.0,0,Non disponible,0,0,Non disponible,0.0,0,Non disponible,0.0,0,Non disponible,Non disponible,0.0,0
1,00000005J,NaN,Non disponible,0.0,0,Non disponible,0,0,Non disponible,0.0,0,Non disponible,0.0,0,Non disponible,Non disponible,0.0,0
2,00000007Y,NaN,Non disponible,0.0,0,Non disponible,0,0,Non disponible,0.0,0,Non disponible,0.0,0,Non disponible,Non disponible,0.0,0
3,00000018K,NaN,Non disponible,0.0,0,Non disponible,0,0,Non disponible,0.0,0,Non disponible,0.0,0,Non disponible,Non disponible,0.0,0
4,00000019F,2017.0,rouge,1387419.2,10,vert,0,0,vert,0.0,3,jaune,1300705.5,8,vert,jaune,4084830.5,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19573,00000405L,2025.0,Non disponible,0.0,0,vert,0,0,Non disponible,0.0,0,Non disponible,0.0,0,vert,vert,0.0,3
19636,00000406W,2020.0,rouge,34796840.0,20,vert,0,0,jaune,1224616.2,6,orange,32622037.5,16,vert,orange,135240774.5,15
19690,00000406W,2022.0,rouge,34796840.0,20,vert,0,0,jaune,1224616.2,6,orange,32622037.5,16,vert,orange,135240774.5,15
19744,00000406W,2023.0,rouge,34796840.0,20,vert,0,0,jaune,1224616.2,6,orange,32622037.5,16,vert,orange,135240774.5,15
19798,00000406W,2024.0,rouge,36518051.2,20,vert,0,0,jaune,618885.6,6,orange,34235673.0,16,vert,orange,133374348.5,15

In [29]:
df_result = ImportExportIndicators.calculate_indicator_3(df_input, risk_df=df_result)
df_result = ImportExportIndicators.calculate_indicator_4(df_input, risk_df=df_result)
df_result = ImportExportIndicators.calculate_indicator_5(df_input, risk_df=df_result)
df_result

/media/Data/DGI/project/ana_risk/src/indicateurs/import_export_indicators.py:171: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '381949977.6' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  risk_df.loc[mask, "GAP_IND_4"] = result[0]
/media/Data/DGI/project/ana_risk/src/indicateurs/import_export_indicators.py:276: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '14839562.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  risk_df.loc[mask, "GAP_IND_5"] = result[0]

,NUM_IFU,ANNEE,RISQUE_IND_1,GAP_IND_1,SCORE_IND_1,RISQUE_IND_2,GAP_IND_2,SCORE_IND_2,RISQUE_IND_12,GAP_IND_12,...,GAP_IND_13,SCORE_IND_13,RISQUE_IND_3,AGE_MOIS_IND_3,RISQUE_IND_4,GAP_IND_4,SCORE_IND_4,RISQUE_IND_5,GAP_IND_5,SCORE_IND_5
0,00000003T,NaN,Non disponible,0.0,0,Non disponible,0,0,Non disponible,0.0,...,0.0,0,Non disponible,0,Non disponible,0.0,0,Non disponible,0.0,0
1,00000005J,NaN,Non disponible,0.0,0,Non disponible,0,0,Non disponible,0.0,...,0.0,0,Non disponible,0,Non disponible,0.0,0,Non disponible,0.0,0
2,00000007Y,NaN,Non disponible,0.0,0,Non disponible,0,0,Non disponible,0.0,...,0.0,0,Non disponible,0,Non disponible,0.0,0,Non disponible,0.0,0
3,00000018K,NaN,Non disponible,0.0,0,Non disponible,0,0,Non disponible,0.0,...,0.0,0,Non disponible,0,Non disponible,0.0,0,Non disponible,0.0,0
4,00000019F,2017.0,rouge,1387419.2,10,vert,0,0,vert,0.0,...,4084830.5,6,Non disponible,0,vert,0.0,0,vert,0.0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19573,00000405L,2025.0,Non disponible,0.0,0,vert,0,0,Non disponible,0.0,...,0.0,3,Non disponible,0,vert,0.0,0,vert,0.0,3
19636,00000406W,2020.0,rouge,34796840.0,20,vert,0,0,jaune,1224616.2,...,135240774.5,15,Non disponible,0,vert,0.0,0,vert,0.0,3
19690,00000406W,2022.0,rouge,34796840.0,20,vert,0,0,jaune,1224616.2,...,135240774.5,15,Non disponible,0,vert,0.0,0,vert,0.0,3
19744,00000406W,2023.0,rouge,34796840.0,20,vert,0,0,jaune,1224616.2,...,135240774.5,15,Non disponible,0,vert,0.0,0,vert,0.0,3
19798,00000406W,2024.0,rouge,36518051.2,20,vert,0,0,jaune,618885.6,...,133374348.5,15,Non disponible,0,vert,0.0,0,vert,0.0,3

In [30]:
df_result =  ComptabiliteIndicators.calculate_indicator_20(df_input, risk_df=df_result)
#df_result =  ComptabiliteIndicators.calculate_indicator_21(df_input, risk_df=df_result)
#df_result =  ComptabiliteIndicators.calculate_indicator_23(df_input, risk_df=df_result)
df_result =  ComptabiliteIndicators.calculate_indicator_27(df_input, risk_df=df_result)
#df_result =  ComptabiliteIndicators.calculate_indicator_29(df_input, risk_df=df_result)

In [31]:

df_result=  ControleIndicators.calculate_indicator_15(df_input, risk_df=df_result)
df_result =  ControleIndicators.calculate_indicator_16(df_input, risk_df=df_result)

In [32]:
#df_result =AdvancedIndicators.calculate_indicator_37(df_input, risk_df=df_result)
df_result =AdvancedIndicators.calculate_indicator_38(df_input, risk_df=df_result)
df_result =AdvancedIndicators.calculate_indicator_39(df_input, risk_df=df_result)
df_result =AdvancedIndicators.calculate_indicator_46(df_input, risk_df=df_result)
df_result =AdvancedIndicators.calculate_indicator_47(df_input, risk_df=df_result)
df_result =AdvancedIndicators.calculate_indicator_49(df_input, risk_df=df_result)
df_result =AdvancedIndicators.calculate_indicator_57(df_input, risk_df=df_result)
df_result =AdvancedIndicators.calculate_indicator_58(df_input, risk_df=df_result)

In [33]:
df_result.to_csv("data/df_result.csv", index=False)
df_result.to_excel("data/df_result.xlsx", index=False)

In [7]:
df_merged.duplicated(subset=["NUM_IFU" ,"ANNEE"]).value_counts()

True     1692762
False     205074
Name: count, dtype: int64

In [18]:
risk_file ='./data/df_result.csv'
df_risk = pd.read_csv(risk_file)

In [27]:
df_merged.duplicated().value_counts()

False    1831861
True       65975
Name: count, dtype: int64

In [30]:
df_risk["NUM_IFU"] =df_merged["NUM_IFU"]
df_risk["ANNEE"] =df_merged["ANNEE"]

In [19]:
df_risk.shape

(240, 40)

In [21]:
df_risk.drop_duplicates(subset="NUM_IFU", inplace=True)

In [17]:

df_risk.to_csv(risk_file, index=False)

In [9]:
df_merged_mini =df_merged[:1000].copy()
df_merged_mini

,ID_CONTR,NUM_IFU,NOM_x,NOM_MINEFID_x,DATE_CREATION,DATE_IMMAT_x,ETAT,TEL,EMAIL,CODE_FJ,...,ANNEE_FISCAL_y,CODE_ELT_LIQ,VALEUR_NUMERIQUE,TYPE_BENEFICE,DATE_IMMAT_y,NOM_MINEFID_y,DATE_DERNIERE_VG,DATE_DERNIERE_VP,DATE_DERNIERE_AVIS,DERNIERE_GESTION_SOUMIS_VERIF
0,455301,00000003T,MAROU LENGLENGUE,MAROU LENGLENGUE,2006-01-12,2006-01-13,ACTIF,70-11-29-77,NaN,43,...,NaN,NaN,NaN,NaN,2006-01-13 00:00:00,MAROU LENGLENGUE,NaN,NaN,NaN,NaN
1,455656,00000005J,MAHAMADI ZOUNGRANA,MAHAMADI ZOUNGRANA (ETS WEND KONTA (EWK)),2006-02-03,2006-02-03,ACTIF,50303511,NaN,43,...,NaN,NaN,NaN,NaN,2006-02-03 00:00:00,MAHAMADI ZOUNGRANA (ETS WEND KONTA (EWK)),NaN,NaN,NaN,NaN
2,455304,00000007Y,CLEMENT BASSONO,CLEMENT BASSONO (GENIE MULTI-SERVICES),2006-01-12,2006-01-13,ACTIF,70-23-96-06,NaN,43,...,NaN,NaN,NaN,NaN,2006-01-13 00:00:00,CLEMENT BASSONO (GENIE MULTI-SERVICES),NaN,NaN,NaN,NaN
3,455310,00000018K,LAMOUSSA HAMED GANEMTORE,LAMOUSSA HAMED GANEMTORE (UNIVERSE AFRICA TOWI...,2006-01-16,2006-01-16,ACTIF,50-37-19-15,NaN,43,...,NaN,NaN,NaN,NaN,2006-01-16 00:00:00,LAMOUSSA HAMED GANEMTORE (UNIVERSE AFRICA TOWI...,NaN,NaN,NaN,NaN
4,455374,00000019F,SYNOVIE SARL,SYNOVIE SARL,2006-01-16,2006-01-16,ACTIF,50/36/10/92,NIKIEMAD@HOTMAIL.COM,20,...,2019.0,70.0,77282000.0,IS,2006-01-16 00:00:00,SYNOVIE SARL,2022-12-08 00:00:00,NaN,2023-02-13 00:00:00,2023.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,455374,00000019F,SYNOVIE SARL,SYNOVIE SARL,2006-01-16,2006-01-16,ACTIF,50/36/10/92,NIKIEMAD@HOTMAIL.COM,20,...,2021.0,70.0,-12056191.0,IS,2006-01-16 00:00:00,SYNOVIE SARL,2022-12-08 00:00:00,NaN,2023-02-13 00:00:00,2023.0
996,455374,00000019F,SYNOVIE SARL,SYNOVIE SARL,2006-01-16,2006-01-16,ACTIF,50/36/10/92,NIKIEMAD@HOTMAIL.COM,20,...,2021.0,76.0,0.0,IS,2006-01-16 00:00:00,SYNOVIE SARL,2022-12-08 00:00:00,NaN,2023-02-13 00:00:00,2023.0
997,455374,00000019F,SYNOVIE SARL,SYNOVIE SARL,2006-01-16,2006-01-16,ACTIF,50/36/10/92,NIKIEMAD@HOTMAIL.COM,20,...,2021.0,69.0,165065401.0,IS,2006-01-16 00:00:00,SYNOVIE SARL,2022-12-08 00:00:00,NaN,2023-02-13 00:00:00,2023.0
998,455374,00000019F,SYNOVIE SARL,SYNOVIE SARL,2006-01-16,2006-01-16,ACTIF,50/36/10/92,NIKIEMAD@HOTMAIL.COM,20,...,2021.0,74.0,0.0,IS,2006-01-16 00:00:00,SYNOVIE SARL,2022-12-08 00:00:00,NaN,2023-02-13 00:00:00,2023.0
999,455374,00000019F,SYNOVIE SARL,SYNOVIE SARL,2006-01-16,2006-01-16,ACTIF,50/36/10/92,NIKIEMAD@HOTMAIL.COM,20,...,2021.0,71.0,1000000.0,IS,2006-01-16 00:00:00,SYNOVIE SARL,2022-12-08 00:00:00,NaN,2023-02-13 00:00:00,2023.0

In [ ]:
df_insd = pd.read_csv(total_insd_file ,chunksize=1000)
first_chunk = next(df_insd)
first_chunk.head()

,NumActionn,Numid,Nom,Prenom,Nationalite,CapitalMontant,CapitalPourcentage,source_file,ID_BilanActif,AD_ImmobIncorp_Note,...,EntretienRéparatBiensImmobiliers,EntretienRéparationMobiliers,PublicitéPublicationsRelationPublique,FraisTélécommunications,RémunérationIntermédiairesConseil,TT_TransfCharges,VStocks_March,VStocks_MatPremieres,VStocks_Encours,VStocks_ProdFab
0,113610.0,DDG2012B080-2023,NaN,NaN,NaN,0.0,0.0,ActionnAssocPrinc,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,113611.0,KKP2017B150-2023,NaN,NaN,NaN,0.0,0.0,ActionnAssocPrinc,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,113612.0,OUA2017B3649-2023,NaN,NaN,NaN,0.0,0.0,ActionnAssocPrinc,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,113613.0,OUA2017M9489-2023,NaN,NaN,NaN,0.0,0.0,ActionnAssocPrinc,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,113614.0,OUA2009A985-2023,NaN,NaN,NaN,0.0,0.0,ActionnAssocPrinc,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# calcul indicateur

In [9]:
ind_1 = TVAIndicators.calculate_indicator_1(merged_data=df_merged)
ind_1

,ID_CONTR,NUM_IFU,NOM_x,NOM_MINEFID_x,DATE_CREATION,DATE_IMMAT_x,ETAT,TEL,EMAIL,CODE_FJ,...,TYPE_BENEFICE,DATE_IMMAT_y,NOM_MINEFID_y,DATE_DERNIERE_VG,DATE_DERNIERE_VP,DATE_DERNIERE_AVIS,DERNIERE_GESTION_SOUMIS_VERIF,RISQUE_IND_1,GAP_IND_1,SCORE_IND_1
0,455301,00000003T,MAROU LENGLENGUE,MAROU LENGLENGUE,2006-01-12,2006-01-13,ACTIF,70-11-29-77,NaN,43,...,NaN,2006-01-13 00:00:00,MAROU LENGLENGUE,NaN,NaN,NaN,NaN,Non disponible,0.0,0.0
1,455656,00000005J,MAHAMADI ZOUNGRANA,MAHAMADI ZOUNGRANA (ETS WEND KONTA (EWK)),2006-02-03,2006-02-03,ACTIF,50303511,NaN,43,...,NaN,2006-02-03 00:00:00,MAHAMADI ZOUNGRANA (ETS WEND KONTA (EWK)),NaN,NaN,NaN,NaN,Non disponible,0.0,0.0
2,455304,00000007Y,CLEMENT BASSONO,CLEMENT BASSONO (GENIE MULTI-SERVICES),2006-01-12,2006-01-13,ACTIF,70-23-96-06,NaN,43,...,NaN,2006-01-13 00:00:00,CLEMENT BASSONO (GENIE MULTI-SERVICES),NaN,NaN,NaN,NaN,Non disponible,0.0,0.0
3,455310,00000018K,LAMOUSSA HAMED GANEMTORE,LAMOUSSA HAMED GANEMTORE (UNIVERSE AFRICA TOWI...,2006-01-16,2006-01-16,ACTIF,50-37-19-15,NaN,43,...,NaN,2006-01-16 00:00:00,LAMOUSSA HAMED GANEMTORE (UNIVERSE AFRICA TOWI...,NaN,NaN,NaN,NaN,Non disponible,0.0,0.0
4,455374,00000019F,SYNOVIE SARL,SYNOVIE SARL,2006-01-16,2006-01-16,ACTIF,50/36/10/92,NIKIEMAD@HOTMAIL.COM,20,...,IS,2006-01-16 00:00:00,SYNOVIE SARL,2022-12-08 00:00:00,NaN,2023-02-13 00:00:00,2023.0,rouge,20117008.8,20.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1897831,1088105,00254499U,FULBERT NOOMAN DINABA,FULBERT NOOMAN DINABA (NOOMAN MULTI SERVICES),2024-12-13 16:56:43,2024-12-13 17:56:43,ACTIF,70-66-86-11,dinabaflubert@gmail.com,43,...,NaN,2024-12-13 17:56:43,FULBERT NOOMAN DINABA (NOOMAN MULTI SERVICES),NaN,NaN,NaN,NaN,Non disponible,0.0,0.0
1897832,1088106,00254500J,ISSA COMPAORE,ISSA COMPAORE (COMISSA AUTOMOBILE),2024-12-13 17:04:11,2024-12-13 18:04:11,ACTIF,78-61-19-63,compaore@gmail.com,43,...,NaN,2024-12-13 18:04:11,ISSA COMPAORE (COMISSA AUTOMOBILE),NaN,NaN,NaN,NaN,Non disponible,0.0,0.0
1897833,1088093,00254501P,FAUCON PELERIN SECURITY,FAUCON PELERIN SECURITY (FAUCON PELERIN SECUR...,2024-12-13 17:05:49,2024-12-13 18:05:49,ACTIF,78-00-91-35,NaN,20,...,NaN,2024-12-13 18:05:49,FAUCON PELERIN SECURITY (FAUCON PELERIN SECUR...,NaN,NaN,NaN,NaN,Non disponible,0.0,0.0
1897834,1088107,00254502Y,ZOUNGRANA IBRAHIM MATERIAUX,ZOUNGRANA IBRAHIM MATERIAUX (ZOUNGRANA IBRAHI...,2024-12-13 17:07:20,2024-12-13 18:07:20,ACTIF,78-59-22-72,NaN,20,...,NaN,2024-12-13 18:07:20,ZOUNGRANA IBRAHIM MATERIAUX (ZOUNGRANA IBRAHI...,NaN,NaN,NaN,NaN,Non disponible,0.0,0.0
1897835,1088117,00254503N,TIDIANI SANOGO,TIDIANI SANOGO,2024-12-14 11:58:01,2024-12-14 12:58:01,ACTIF,+226-70-50-94-10,NaN,43,...,NaN,2024-12-14 12:58:01,TIDIANI SANOGO,NaN,NaN,NaN,NaN,Non disponible,0.0,0.0

In [ ]:
df_merged.duplicated().value_counts()

False    1831861
True       65975
Name: count, dtype: int64

In [4]:
columns = ["NUM_IFU", "code_structure", "libelle_structure", "raison_sociale", 
           "periode_fiscale", "etat", "regime_fiscale", "date_debut_activite", 
           "secteur_activite", "type_controle", "forme_juridique", 
           "hierarchie_2", "hierarchie_3"]
df=pd.DataFrame(columns=columns)
df.to_csv("./data/df_risk_30_07_2025.csv", index=False)

In [20]:
cols = [
 'NUM_IFU',
 'ANNEE',
 'CODE_STRUCTURE',
 'LIBELLE_STRUCTURE',
 'RAISON_SOCIALE',
 'PERIODE_FISCALE',
 'ETAT',
 'REGIME_FISCALE',
 'DATE_DEBUT_ACTIVITE',
 'SECTEUR_ACTIVITE',
 'TYPE_CONTROLE',
 'FORME_JURIDIQUE',
 'HIERARCHIE_2',
 'HIERARCHIE_3',
 'HIERARCHIE_2',
 'HIERARCHIE_3',
 'RISQUE_IND_1',
 'GAP_IND_1',
 'SCORE_IND_1',
 'RISQUE_IND_2',
 'GAP_IND_2',
 'SCORE_IND_2',
 'RISQUE_IND_12',
 'GAP_IND_12',
 'SCORE_IND_12',
 'RISQUE_IND_8',
 'GAP_IND_8',
 'SCORE_IND_8',
 'RISQUE_IND_14',
 'RISQUE_IND_13',
 'GAP_IND_13',
 'SCORE_IND_13',
 'RISQUE_IND_3',
 'AGE_MOIS_IND_3',
 'RISQUE_IND_4',
 'GAP_IND_4',
 'SCORE_IND_4',
 'RISQUE_IND_5',
 'GAP_IND_5',
 'SCORE_IND_5',
 'RISQUE_IND_20',
 'GAP_IND_20',
 'SCORE_IND_20',
 'RISQUE_IND_27',
 'RISQUE_IND_15_A',
 'RISQUE_IND_15_B',
 'RISQUE_IND_16',
 'RISQUE_IND_38',
 'RISQUE_IND_39',
 'RISQUE_IND_46',
 'RISQUE_IND_47',
 'RISQUE_IND_49',
 'RISQUE_IND_57',
 'RISQUE_IND_58']

In [21]:
df_model = pd.DataFrame(columns=cols)
df_model.to_csv("./data/df_model.csv", index=False)

In [22]:
cols = df_risk.columns.tolist()
for col in cols:
    if col  in df_model.columns:
        df_model[col] = df_risk[col]

In [23]:
df_model.head()

,NUM_IFU,ANNEE,CODE_STRUCTURE,LIBELLE_STRUCTURE,RAISON_SOCIALE,PERIODE_FISCALE,ETAT,REGIME_FISCALE,DATE_DEBUT_ACTIVITE,SECTEUR_ACTIVITE,...,RISQUE_IND_15_A,RISQUE_IND_15_B,RISQUE_IND_16,RISQUE_IND_38,RISQUE_IND_39,RISQUE_IND_46,RISQUE_IND_47,RISQUE_IND_49,RISQUE_IND_57,RISQUE_IND_58
0,00000003T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Non disponible,Non disponible,Non disponible,Non disponible,Non disponible,Non disponible,Non disponible,Non disponible,Non disponible,Non disponible
1,00000005J,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Non disponible,Non disponible,Non disponible,Non disponible,Non disponible,Non disponible,Non disponible,Non disponible,Non disponible,Non disponible
2,00000007Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Non disponible,Non disponible,Non disponible,Non disponible,Non disponible,Non disponible,Non disponible,Non disponible,Non disponible,Non disponible
3,00000018K,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Non disponible,Non disponible,Non disponible,Non disponible,Non disponible,Non disponible,Non disponible,Non disponible,Non disponible,Non disponible
4,00000019F,2017.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,vert,vert,vert,Non disponible,Non disponible,vert,Non disponible,Non disponible,vert,vert

In [24]:
df_model.dropna(subset=["NUM_IFU", "ANNEE"], inplace=True)

In [25]:
df_model

,NUM_IFU,ANNEE,CODE_STRUCTURE,LIBELLE_STRUCTURE,RAISON_SOCIALE,PERIODE_FISCALE,ETAT,REGIME_FISCALE,DATE_DEBUT_ACTIVITE,SECTEUR_ACTIVITE,...,RISQUE_IND_15_A,RISQUE_IND_15_B,RISQUE_IND_16,RISQUE_IND_38,RISQUE_IND_39,RISQUE_IND_46,RISQUE_IND_47,RISQUE_IND_49,RISQUE_IND_57,RISQUE_IND_58
4,00000019F,2017.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,vert,vert,vert,Non disponible,Non disponible,vert,Non disponible,Non disponible,vert,vert
5,00000019F,2018.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,vert,vert,vert,Non disponible,Non disponible,vert,Non disponible,Non disponible,vert,vert
6,00000019F,2019.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,vert,vert,vert,Non disponible,Non disponible,vert,Non disponible,Non disponible,vert,vert
7,00000019F,2020.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,vert,vert,vert,Non disponible,Non disponible,vert,Non disponible,Non disponible,vert,vert
8,00000019F,2021.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,vert,vert,vert,Non disponible,Non disponible,vert,Non disponible,Non disponible,vert,vert
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,00000405L,2025.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,rouge,rouge,vert,Non disponible,Non disponible,vert,Non disponible,Non disponible,vert,vert
236,00000406W,2020.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,vert,vert,vert,Non disponible,Non disponible,vert,Non disponible,Non disponible,vert,vert
237,00000406W,2022.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,vert,vert,vert,Non disponible,Non disponible,vert,Non disponible,Non disponible,vert,vert
238,00000406W,2023.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,vert,vert,vert,Non disponible,Non disponible,vert,Non disponible,Non disponible,vert,vert
239,00000406W,2024.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,vert,vert,vert,Non disponible,Non disponible,vert,Non disponible,Non disponible,vert,vert

In [26]:
df_model.to_csv("./data/df_model.csv", index=False)