In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
file_ifu_2025 = "./data/IFU_2025.csv"
condification_file = "./insd_tables/CodificationN_1.csv"
ifu_full_file= "./data/IFU_FULL_DGI_28_04_2025.xls"
codification_file = "./insd_tables/CodificationN_1.xlsx"

In [5]:
df_file_ifu_2025 = pd.read_csv(file_ifu_2025, sep=';', encoding='latin-1')
df_file_ifu_2025.head()

,Unnamed: 0,CODE,FORME_J_ABREGE,FORME_JURIDIQUE,STRUCTURES,NUMEROIFU,PRENOMNOM,NOM_RAISON_SOCIALE,ENSEIGNECOMMERCIALE,ETAT,LIEUCREATION,LATITUDE,LONGITUDE,TELEPHONE,SEXE,ACTIVITE
0,1,CME,P.P,PERSONNE PHYSIQUE,DCI-OUAGA 6,00106806X,OUSMANE KABORE,NaN,ENTREPRISE KABORE ET FRERES DE POA,1,OUAGA,NaN,-1,75-03-24-67,2.0,COMMERCE DE DÉTAIL EN MAGASIN SPÉCIALISÉ DE PR...
1,2,RSI,DIVERS,DIVERS,SDI SIDERADOUGOU,00106807K,NaN,COLLEGE PRIVEE JEAN WYCHIFE (LA GRACE),COLLEGE PRIVEE JEAN WYCHIFE (LA GRACE),0,NaN,0,-1,70118389,NaN,ENSEIGNEMENT SECONDAIRE GÉNÉRAL
2,3,CME,P.P,PERSONNE PHYSIQUE,DCI-OUAGA 6,00106791H,AMADO SANFO,NaN,ETABLISSEMENT FAOUSIA SANFO,1,OUAGA,NaN,-1,68-52-58-10,2.0,AUTRES COMMERCES DE GROS
3,4,ND,ASSOCIATION,ASSOCIATION,DME/CENTRE IV,00107075G,NaN,DEVELOPPEMENT LOCAL INCLUSIF COMMUNES GORGADJI...,DEVELOPPEMENT LOCAL INCLUSIF,0,NaN,NaN,-1,25-36-28-71/25-36-28-73/75,NaN,ACTION SOCIALE
4,5,ND,ASSOCIATION,ASSOCIATION,DME/CENTRE IV,00107076S,NaN,DEVELOPPEMENT LOCAL INCLUSF COMMUNES DE FALAGO...,DEVELOPPEMENT LOCAL INCLUSIF,0,NaN,NaN,-1,25-36-28-71/25-36-28-73/75,NaN,ACTION SOCIALE

In [6]:
df_file_ifu_2025.shape

(273168, 16)

In [7]:
df_condification = pd.read_csv(condification_file, sep=',')
df_condification.head()

,Numid,DenominationSociale,SigleUsuel,AdresseComplete,Num_IFU_Contribuable,Activités
0,OUA2006B025-2023,PHARMACIE SONGTAABA,PHARMACIE SONGTAABA,NaN,00000802B,G01008004
1,BFOUA2007A418-2023,SADA KABORE /E.K.F,SADA KABORE /E.K.F,NaN,00010003 C,G01008010
2,OUA2000B971-2023,GENERAL AFFRETEMENT TRANSIT ET TRANSPORT,GATT,NaN,00011668Y,H01005000
3,OUA2002B2226-2023,KABRE SERVICE DISTRIBUTIONS,KABRE SERVICE DISTRIBUTIONS,NaN,00134284 G,G01008009
4,OUA2004B1638-2023,SOCIETE FIDUCIERE COMPTABLE DU BURKINA,SOFICO,NaN,0005260R,M01001002

In [8]:
df_condification.shape

(3060, 6)

In [9]:
df_ifu_full = pd.read_excel(ifu_full_file)
df_ifu_full.head()

WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero

,IDDCI,LIBELLE,STRUCTURES,NUMEROIFU,NOM_RAISON_SOCIALE,ENSEIGNECOMMERCIALE,ETAT,CODE_REGIME,REGIME,CATEGORIE,...,SECTION,LATITUDE,LONGITUDE,SEXE,LIBELLE_SEXE,RESIDENT,TYPE_PROPRIETE,NOTES,ZONE_SPECIALE,INFOSZONESPECIALE
0,37,DIRECTION REGIONALE DES IMPOTS DE LA BOUCLE DU...,BALE,00003166W,BONKOUNGOU MARIAM KINDA /,AUBERGE TOURISTIQUE BELBA,DESACTIVE,RSI,REGIME SIMPLIFIE D'IMPOSITION,POTENTIEL,...,NaN,NaN,-1.0,1.0,FEMININ,1,NaN,NaN,NaN,NaN
1,37,DIRECTION REGIONALE DES IMPOTS DE LA BOUCLE DU...,BALE,00004232A,CENTRE D'ETUDE DE FORMATION ET DE REALISATION,CEFRAP,ACTIF,RSI,REGIME SIMPLIFIE D'IMPOSITION,REEL,...,HL,0.0,-1.0,NaN,NaN,1,NaN,NaN,NaN,NaN
2,37,DIRECTION REGIONALE DES IMPOTS DE LA BOUCLE DU...,BALE,00004727D,BRUNO DAH,PHARMACIE DES BALÉ,DESACTIVE,RSI,REGIME SIMPLIFIE D'IMPOSITION,POTENTIEL,...,NaN,NaN,-1.0,2.0,MASCULIN,1,NaN,NaN,NaN,NaN
3,37,DIRECTION REGIONALE DES IMPOTS DE LA BOUCLE DU...,BALE,00004729L,LASSINA TRAORE,NaN,ACTIF,ND,NON DETERMINE,POTENTIEL,...,AK,NaN,-1.0,2.0,MASCULIN,1,NaN,NaN,NaN,NaN
4,37,DIRECTION REGIONALE DES IMPOTS DE LA BOUCLE DU...,BALE,00004817G,AMADO SANFO,ETS SANFO AMADO,DESACTIVE,RSI,REGIME SIMPLIFIE D'IMPOSITION,POTENTIEL,...,NaN,NaN,-1.0,2.0,MASCULIN,1,NaN,NaN,NaN,NaN

In [10]:
df_ifu_full

,IDDCI,LIBELLE,STRUCTURES,NUMEROIFU,NOM_RAISON_SOCIALE,ENSEIGNECOMMERCIALE,ETAT,CODE_REGIME,REGIME,CATEGORIE,...,SECTION,LATITUDE,LONGITUDE,SEXE,LIBELLE_SEXE,RESIDENT,TYPE_PROPRIETE,NOTES,ZONE_SPECIALE,INFOSZONESPECIALE
0,37,DIRECTION REGIONALE DES IMPOTS DE LA BOUCLE DU...,BALE,00003166W,BONKOUNGOU MARIAM KINDA /,AUBERGE TOURISTIQUE BELBA,DESACTIVE,RSI,REGIME SIMPLIFIE D'IMPOSITION,POTENTIEL,...,NaN,NaN,-1.0,1.0,FEMININ,1,NaN,NaN,NaN,NaN
1,37,DIRECTION REGIONALE DES IMPOTS DE LA BOUCLE DU...,BALE,00004232A,CENTRE D'ETUDE DE FORMATION ET DE REALISATION,CEFRAP,ACTIF,RSI,REGIME SIMPLIFIE D'IMPOSITION,REEL,...,HL,0.0,-1.0,NaN,NaN,1,NaN,NaN,NaN,NaN
2,37,DIRECTION REGIONALE DES IMPOTS DE LA BOUCLE DU...,BALE,00004727D,BRUNO DAH,PHARMACIE DES BALÉ,DESACTIVE,RSI,REGIME SIMPLIFIE D'IMPOSITION,POTENTIEL,...,NaN,NaN,-1.0,2.0,MASCULIN,1,NaN,NaN,NaN,NaN
3,37,DIRECTION REGIONALE DES IMPOTS DE LA BOUCLE DU...,BALE,00004729L,LASSINA TRAORE,NaN,ACTIF,ND,NON DETERMINE,POTENTIEL,...,AK,NaN,-1.0,2.0,MASCULIN,1,NaN,NaN,NaN,NaN
4,37,DIRECTION REGIONALE DES IMPOTS DE LA BOUCLE DU...,BALE,00004817G,AMADO SANFO,ETS SANFO AMADO,DESACTIVE,RSI,REGIME SIMPLIFIE D'IMPOSITION,POTENTIEL,...,NaN,NaN,-1.0,2.0,MASCULIN,1,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64994,64,DIRECTION REGIONALE DES IMPOTS DU CENTRE,DCI-OUAGA 2,00114389G,TAMAM,TAMAM,ACTIF,CMD,CONTRIBUTION DES MICRO-ENTREPRISES RÉGIME DÉCL...,REEL,...,BK,0.0,-1.0,NaN,NaN,1,Locataire,NaN,NaN,NaN
64995,64,DIRECTION REGIONALE DES IMPOTS DU CENTRE,DCI-OUAGA 2,00114392M,ADAMA SINON,ETABLISSEMENT SINON ADAMA,ACTIF,CME,CONTRIBUTION DES MICRO-ENTREPRISES,POTENTIEL,...,NaN,0.0,-1.0,2.0,MASCULIN,1,Propriétaire,NaN,NaN,NaN
64996,64,DIRECTION REGIONALE DES IMPOTS DU CENTRE,DCI-OUAGA 2,00114401Z,IBRAHIM LENE,IBRAHIM CONCEPTION,ACTIF,CME,CONTRIBUTION DES MICRO-ENTREPRISES,POTENTIEL,...,BI,0.0,-1.0,2.0,MASCULIN,1,Locataire,NaN,NaN,NaN
64997,64,DIRECTION REGIONALE DES IMPOTS DU CENTRE,DCI-OUAGA 2,00114423C,HARZOUMA PASCAL MOYANGA,PLOMBERIE SPECIALISTE IRRIGATION,ACTIF,RSI,REGIME SIMPLIFIE D'IMPOSITION,REEL,...,BL,0.0,-1.0,2.0,MASCULIN,1,Locataire,NaN,NaN,NaN
64998,64,DIRECTION REGIONALE DES IMPOTS DU CENTRE,DCI-OUAGA 2,00114473H,RELWENDE COMMENEM ZANGA,RELWENDE COMMENEM ZANGA,ACTIF,CMD,CONTRIBUTION DES MICRO-ENTREPRISES RÉGIME DÉCL...,REEL,...,BY,0.0,-1.0,NaN,NaN,1,Locataire,NaN,NaN,NaN

In [11]:
codification_file = "./insd_tables/CodificationN_1.xlsx"
df_codification = pd.read_excel(codification_file, sheet_name='CodificationN_1')
df_codification

,Numid,DenominationSociale,SigleUsuel,AdresseComplete,Num_IFU_Contribuable,Unnamed: 5,Activités
0,OUA2006B025-2023,PHARMACIE SONGTAABA,PHARMACIE SONGTAABA,NaN,00000802B,9,G01008004
1,BFOUA2007A418-2023,SADA KABORE /E.K.F,SADA KABORE /E.K.F,NaN,00010003C,9,G01008010
2,OUA2000B971-2023,GENERAL AFFRETEMENT TRANSIT ET TRANSPORT,GATT,NaN,00011668Y,9,H01005000
3,OUA2002B2226-2023,KABRE SERVICE DISTRIBUTIONS,KABRE SERVICE DISTRIBUTIONS,NaN,00134284G,9,G01008009
4,OUA2004B1638-2023,SOCIETE FIDUCIERE COMPTABLE DU BURKINA,SOFICO,NaN,00005260R,9,M01001002
...,...,...,...,...,...,...,...
3055,YAKO2015B016-2023,PHARMACIE RIALE SARL,PHARMACIE RIALE,NaN,00065781E,9,G01008004
3056,YKO2012B006-2023,APPRO-MAT SARL,APPRO-MAT SARL,NaN,00037642L,9,F01003000
3057,ZNR2013A050-2023,LYCEE TECHNIQUE PRIVE DES ASSEMBLEES DE DIEU,LTPAD,NaN,00010259E,9,P01000000
3058,ZNR2013M002-2023,SM SERVICES SARL,SM SERVICES,NaN,0033286J,8,G01008010
3059,ZNR2013M002-2023_dbl_2,OUEDRAOGO CONSTANT AC - CONCEPT,0,NaN,00034619U,9,M01005000

In [12]:
ifu_correct = df_codification[df_codification["Num_IFU_Contribuable"].isin(df_file_ifu_2025["NUMEROIFU"])]
ifu_correct

,Numid,DenominationSociale,SigleUsuel,AdresseComplete,Num_IFU_Contribuable,Unnamed: 5,Activités
0,OUA2006B025-2023,PHARMACIE SONGTAABA,PHARMACIE SONGTAABA,NaN,00000802B,9,G01008004
1,BFOUA2007A418-2023,SADA KABORE /E.K.F,SADA KABORE /E.K.F,NaN,00010003C,9,G01008010
2,OUA2000B971-2023,GENERAL AFFRETEMENT TRANSIT ET TRANSPORT,GATT,NaN,00011668Y,9,H01005000
3,OUA2002B2226-2023,KABRE SERVICE DISTRIBUTIONS,KABRE SERVICE DISTRIBUTIONS,NaN,00134284G,9,G01008009
4,OUA2004B1638-2023,SOCIETE FIDUCIERE COMPTABLE DU BURKINA,SOFICO,NaN,00005260R,9,M01001002
...,...,...,...,...,...,...,...
3054,TNK2020B0466-2023,PHARMACIE TIBO SARL,PHARMACIE TIBO,NaN,00142308Y,9,G01008004
3055,YAKO2015B016-2023,PHARMACIE RIALE SARL,PHARMACIE RIALE,NaN,00065781E,9,G01008004
3056,YKO2012B006-2023,APPRO-MAT SARL,APPRO-MAT SARL,NaN,00037642L,9,F01003000
3057,ZNR2013A050-2023,LYCEE TECHNIQUE PRIVE DES ASSEMBLEES DE DIEU,LTPAD,NaN,00010259E,9,P01000000
3059,ZNR2013M002-2023_dbl_2,OUEDRAOGO CONSTANT AC - CONCEPT,0,NaN,00034619U,9,M01005000

In [13]:
ifu_not_correct = df_codification[~df_codification["Num_IFU_Contribuable"].isin(df_file_ifu_2025["NUMEROIFU"])]
ifu_not_correct

,Numid,DenominationSociale,SigleUsuel,AdresseComplete,Num_IFU_Contribuable,Unnamed: 5,Activités
7,OUA2017B3024-2023,INTERNATIONAL MONTAGE MAINTENACE,IMM,NaN,00089495N,9,C09003000
15,00001299P-2023,GROUPE SCOLAIRE NOTRE DAME DE L'ANNONCIATION D...,GSNDAC,NaN,00001299P,9,P01000000
19,00002506L-2023,OUEDRAOGO SAIDOU,OUEDRAOGO SAIDOU,NaN,00002506L,9,G01008005
20,00002506L-2023,OUEDRAOGO SAIDOU,OUEDRAOGO SAIDOU,NaN,00002506L,9,G01008005
21,00002506L-2023,OUEDRAOGO SAIDOU,OUEDRAOGO SAIDOU,NaN,00002506L,9,G01008005
...,...,...,...,...,...,...,...
2965,OUA2021M7546-2023,ADAN GROUPE SA,ADAN GROUPE,NaN,000154635P,10,F01001000
2985,OUA2022B3635-2023,MASSAKA SAS,MASSAKA,NaN,001775072K,10,J01005000
2993,OUA2022M11307-2023,CENTRALE COMMERCIALE DU FASO LOGISTICS,CECOFA LOGISTICS SA,NaN,00036192/M,10,H01005000
3010,OUA212B5424-2023,PHARMACIE DU MUSEE,0,NaN,00043433Y,9,G01008004
3058,ZNR2013M002-2023,SM SERVICES SARL,SM SERVICES,NaN,0033286J,8,G01008010