In [1]:
import os
import sys
from core.data_loader import DataLoader
from db.ods import connectionOds
from core.risk_compute import RiskComputer
from data_extractor import DataExtractor
from sqlalchemy import create_engine
from core import sql_ifu
from dotenv import load_dotenv
load_dotenv()

True

In [2]:

# Initialisation des connexions aux bases de données
oracle_engine = connectionOds()
connect = oracle_engine.connect()

#print(f"Postgres DB Host: {POSTGRES_DB_HOST} Port: {POSTGRES_DB_PORT} User: {POSTGRES_DB_USER} DB: {POSTGRES_DB_NAME}")

In [3]:
ifu_db_url = os.getenv("IFU_DB_URL")
ODS_DB_URL = os.getenv("ODS_DB_URL")

In [4]:
print(f"IFU DB URL: {ifu_db_url}")

IFU DB URL: oracle+oracledb://toussaintifu:toussaint2025@10.1.0.10:1521/?service_name=IFU3

In [5]:
extractor = DataExtractor()
#ifubase.dgi.bf:1521/IFU3
url = f"oracle+oracledb://toussaintifu:toussaint2025@10.1.0.10:1521/?service_name=IFU3"
engin = create_engine(ifu_db_url).connect()

In [6]:
data_fu = extractor.extract_data(engin, sql_ifu)

In [8]:
data_fu

,structures,num_ifu,latitude,longitude,activites_ifu
0,DCI-OUAGA 6,00106806X,NaN,-1.0,COMMERCE DE DÉTAIL EN MAGASIN SPÉCIALISÉ DE PR...
1,SDI SIDERADOUGOU,00106807K,0.0,-1.0,ENSEIGNEMENT SECONDAIRE GÉNÉRAL
2,DCI-OUAGA 6,00106791H,NaN,-1.0,AUTRES COMMERCES DE GROS
3,DME/CENTRE IV,00107075G,NaN,-1.0,ACTION SOCIALE
4,DME/CENTRE IV,00107076S,NaN,-1.0,ACTION SOCIALE
...,...,...,...,...,...
303232,KOURITENGA,00298335H,0.0,0.0,AUTRES ACTIVITÉS DE SERVICES PERSONNELS
303233,DCI-OUAGA 6,00298336T,0.0,0.0,CONSTRUCTION DES BÂTIMENTS
303234,SDI N'DOROLA,00298343G,0.0,0.0,COMMERCE DE DÉTAIL EN MAGASIN NON SPÉCIALISÉ
303235,DCI-OUAGA 5,00298345D,0.0,0.0,TRAVAUX D'INSTALLATION
303236,DCI-OUAGA 4,00295236N,0.0,0.0,COMMERCE DE DÉTAIL EN MAGASIN SPÉCIALISÉ DE MA...

In [7]:
engin_ods = create_engine(ODS_DB_URL).connect()

In [9]:
sql =""" select * from SID_DGD_CPF"""
dgd_data = extractor.extract_data(engin_ods, sql)

In [10]:
dgd_data

,sid_dgdid,instanceid,code_bureau,lib_bureau,num_liquidation,date_liquidation,num_article,nomenclature8,nomenclature10,libelle,...,annee_exo,numero_exo,ref_base_legale,etat,annulee,tep,tpc,tvt,mt_liquid,date_charge
0,1480969,1382224,BFC04,OUAGA ROUTE,L27,2017-01-04,4,20087000,2008700000,"PECHES, Y C. BRUGNONS, NECTARINES AUTREMEN PRE...",...,None,None,None,None,0.0,NaN,NaN,NaN,2336515.0,2022-09-28 23:52:08
1,2683736,3626168,BFC04,OUAGA ROUTE,L18588,2022-07-22,1,84145100,8414510000,"VENTILATEURS DE TABLE,DE SOL,MURAUX,PLAFONNIER...",...,None,None,None,None,0.0,NaN,NaN,NaN,1425636.0,2022-09-28 23:52:08
2,2683762,3626200,BFC04,OUAGA ROUTE,L18982,2022-07-27,4,95066200,9506620000,BALLONS ET BALLES GONFLABLES,...,None,None,None,None,0.0,NaN,NaN,NaN,11002750.0,2022-09-28 23:52:08
3,2683792,3626228,BFC02,OUAGA AEROPORT,L8154,2022-07-25,10,85334000,8533400000,RESISTANCES ELECTRIQ VARIABLES(Y COMPRIS RHEOS...,...,2022,16428,2018-003/MMC/MINEFID,None,0.0,NaN,NaN,NaN,2038950.0,2022-09-28 23:52:08
4,1480819,1294260,BFC02,OUAGA AEROPORT,L4706,2017-04-13,1,82071900,8207190000,"OUTILS DE FORAGE OU DE SONDAGE,AVEC PARTIE TRA...",...,None,None,None,None,0.0,NaN,NaN,NaN,10823255.0,2022-09-28 23:52:08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2180854,45747893,5129072,BFC02,OUAGA AEROPORT,L4282,2026-04-09,2,84212900,8421290000,APPAREIL POUR LA FILTRATION OU L'EPURATION DES...,...,None,None,None,None,0.0,NaN,NaN,NaN,1084313.0,2026-04-10 07:28:16
2180855,45747314,5120827,BFC01,OUAGA GARE,L1676,2026-04-09,4,70179000,7017900000,"VERRERIE DE LABO,D'HYGIENE OU DE PHARMACIE MEM...",...,None,None,None,None,0.0,NaN,NaN,NaN,6269371.0,2026-04-10 07:28:16
2180856,45747603,5128509,BFC03,OUAGA CDP,L2507,2026-04-09,2,42029990,4202999000,ETUIS A CIGARETT…SAC D VOYAGE…ECRIN…SURF EXT E...,...,None,None,None,None,0.0,NaN,NaN,NaN,118257.0,2026-04-10 07:28:16
2180857,45748143,5129552,BFC15,BVA (BUREAU VEHICULES AUTOMOBILES),L15655,2026-04-09,1,87032320,8703232090,"VEHICULE USAGE,A MOTEUR A PISTON ALLUM PAR ETI...",...,None,None,None,None,0.0,NaN,NaN,NaN,594438.0,2026-04-10 07:28:16
2180858,45747617,5128581,BFC02,OUAGA AEROPORT,L4285,2026-04-09,5,73269090,7326909000,OUVRAGES EN FER OU EN ACIER NON SPECIFIES DANS...,...,None,None,None,None,0.0,NaN,NaN,NaN,5967449.0,2026-04-10 07:28:16

In [3]:
loader = DataLoader(oracle_engine)
computer = RiskComputer()

2026-04-08 17:33:50,517 - core.data_loader - INFO - Chargement des données de référence...
2026-04-08 17:33:50,689 - core.data_loader - INFO - NON_EIGIBLE.xlsx chargé: 6204 IFU exclus
2026-04-08 17:33:50,708 - core.data_loader - INFO - Entreprises_LIEES.xlsx chargé: 100 lignes
2026-04-08 17:33:50,723 - core.data_loader - INFO - ../docs/META_DONNEES.xlsx chargé
2026-04-08 17:33:50,727 - core.data_loader - INFO - ../docs/FICHE_PISTES_INVESTIGATION.xlsx chargé
2026-04-08 17:33:50,841 - core.data_loader - INFO - ../docs/NomenclatureSH.xlsx chargé
2026-04-08 17:33:50,857 - core.data_loader - INFO - ../docs/DCF_ACTIVITES.xlsx chargé
2026-04-08 17:33:50,857 - core.risk_compute - INFO - Chargement des données de référence...
2026-04-08 17:33:51,105 - core.risk_compute - INFO - NON_EIGIBLE.xlsx chargé: 6984 IFU a exclur
2026-04-08 17:33:51,116 - core.risk_compute - INFO - Entreprises_LIEES.xlsx chargé: 100 lignes

In [4]:
from core.fiches_generator import FichesGenerator
import pandas as pd

In [ ]:
quantume ="Q2_2025"
with oracle_engine.connect() as connection:
            ifu_data = loader.extract_ifu(connection)
            data_dgd = loader.extract_dgd(connection)

risk_data_path = f"../data/risk_contribuables/{quantume}.csv"
quantume_path  = f"../programmes/{quantume}.xlsx"
quantume=pd.read_excel(quantume_path)
risk_data=pd.read_csv(risk_data_path,sep=";")
generator = FichesGenerator(quantume_name=quantume,
                                    quantume=quantume,
                                    ifu_data=ifu_data,
                                    risk_data=risk_data,
                                    data_dgd=data_dgd)
generator.generate()

2026-04-08 17:34:14,211 - core.data_loader - INFO - Extraction IFU complète
2026-04-08 17:34:16,321 - core.data_loader - INFO - IFU chargée depuis le cache: ../data/data_ifu.csv
2026-04-08 17:34:16,321 - core.data_loader - INFO - IFU complète extraite: 677677 lignes en 2.11s
2026-04-08 17:34:16,321 - core.data_loader - INFO - Extraction DGD complète avec nomenclature
2026-04-08 17:34:16,356 - core.data_loader - INFO - DGD chargée depuis le cache: ../data/data_douanes.csv
2026-04-08 17:34:16,357 - core.data_loader - INFO - DGD complète extraite: 38513 lignes en 0.04s
2026-04-08 17:34:16,411 - core.fiches_generator - INFO - Chargement des données de référence...
2026-04-08 17:34:16,421 - core.fiches_generator - INFO - ../docs/META_DONNEES.xlsx chargé
2026-04-08 17:34:16,421 - core.fiches_generator - INFO - ../docs/FICHE_PISTES_INVESTIGATION.xlsx chargé
2026-04-08 17:34:16,537 - core.fiches_generator - INFO - ../docs/NomenclatureSH.xlsx chargé
2026-04-08 17:34:16,554 - core.fiches_generator - INFO - ../docs/DCF_ACTIVITES.xlsx chargé
2026-04-08 17:34:16,572 - core.fiches_generator - INFO - ../docs/SUIVI.xlsx chargé
2026-04-08 17:34:16,854 - core.fiches_generator - INFO - Répertoire de programme créé: ../fiches\Q2_2025
2026-04-08 17:34:16,854 - core.fiches_generator - ERROR - Erreur lors de la génération de la fiche pour 00021356D: join() argument must be str, bytes, or os.PathLike object, not 'float'
2026-04-08 17:34:16,854 - core.fiches_generator - ERROR - Erreur lors de la génération de la fiche pour 00003877M: join() argument must be str, bytes, or os.PathLike object, not 'float'
2026-04-08 17:34:16,854 - core.fiches_generator - ERROR - Erreur lors de la génération de la fiche pour 00066918S: join() argument must be str, bytes, or os.PathLike object, not 'float'
2026-04-08 17:34:16,854 - core.fiches_generator - ERROR - Erreur lors de la génération de la fiche pour 00048272K: join() argument must be str, bytes, or os.PathLike object, not 'float'
2026-04-08 17:34:16,854 - core.fiches_generator - ERROR - Erreur lors de la génération de la fiche pour 00060978J: join() argument must be str, bytes, or os.PathLike object, not 'float'
2026-04-08 17:34:16,854 - core.fiches_generator - ERROR - Erreur lors de la génération de la fiche pour 00080666J: join() argument must be str, bytes, or os.PathLike object, not 'float'
2026-04-08 17:34:16,854 - core.fiches_generator - ERROR - Erreur lors de la génération de la fiche pour 00128041A: join() argument must be str, bytes, or os.PathLike object, not 'float'
2026-04-08 17:34:16,854 - core.fiches_generator - ERROR - Erreur lors de la génération de la fiche pour 00132794W: join() argument must be str, bytes, or os.PathLike object, not 'float'
2026-04-08 17:34:16,854 - core.fiches_generator - ERROR - Erreur lors de la génération de la fiche pour 00128844C: join() argument must be str, bytes, or os.PathLike object, not 'float'
2026-04-08 17:34:16,854 - core.fiches_generator - ERROR - Erreur lors de la génération de la fiche pour 00054890D: join() argument must be str, bytes, or os.PathLike object, not 'float'
2026-04-08 17:34:16,854 - core.fiches_generator - ERROR - Erreur lors de la génération de la fiche pour 00001496E: join() argument must be str, bytes, or os.PathLike object, not 'float'
2026-04-08 17:34:16,854 - core.fiches_generator - ERROR - Erreur lors de la génération de la fiche pour 00142129D: join() argument must be str, bytes, or os.PathLike object, not 'float'
2026-04-08 17:34:16,854 - core.fiches_generator - ERROR - Erreur lors de la génération de la fiche pour 00013267F: join() argument must be str, bytes, or os.PathLike object, not 'float'
2026-04-08 17:34:16,854 - core.fiches_generator - ERROR - Erreur lors de la génération de la fiche pour 00072659H: join() argument must be str, bytes, or os.PathLike object, not 'float'
2026-04-08 17:34:16,854 - core.fiches_generator - ERROR - Erreur lors de la génération de la fiche pour 00135010A: join() argument must be str, bytes, or os.PathLike object, not 'float'
2026-04-08 17:34:16,868 - core.fiches_generator - ERROR - Erreur lors de la génération de la fiche pour 00149922N: join() argument must be str, bytes, or os.PathLike object, not 'float'
2026-04-08 17:34:16,869 - core.fiches_generator - ERROR - Erreur lors de la génération de la fiche pour 00138126S: join() argument must be str, bytes, or os.PathLike object, not 'float'
2026-04-08 17:34:16,870 - core.fiches_generator - ERROR - Erreur lors de la génération de la fiche pour 00052658S: join() argument must be str, bytes, or os.PathLike object, not 'float'
2026-04-08 17:34:16,871 - core.fiches_generator - ERROR - Erreur lors de la génération de la fiche pour 00005053R: join() argument must be str, bytes, or os.PathLike object, not 'float'
2026-04-08 17:34:16,871 - core.fiches_generator - ERROR - Erreur lors de la génération de la fiche pour 00042757A: join() argument must be str, bytes, or os.PathLike object, not 'float'
2026-04-08 17:34:16,872 - core.fiches_generator - ERROR - Erreur lors de la génération de la fiche pour 00120164D: join() argument must be str, bytes, or os.PathLike object, not 'float'
2026-04-08 17:34:16,872 - core.fiches_generator - ERROR - Erreur lors de la génération de la fiche pour 00004485A: join() argument must be str, bytes, or os.PathLike object, not 'float'
2026-04-08 17:34:16,872 - core.fiches_generator - ERROR - Erreur lors de la génération de la fiche pour 00022087Y: join() argument must be str, bytes, or os.PathLike object, not 'float'
2026-04-08 17:34:16,872 - core.fiches_generator - ERROR - Erreur lors de la génération de la fiche pour 00170089U: join() argument must be str, bytes, or os.PathLike object, not 'float'
2026-04-08 17:34:16,872 - core.fiches_generator - INFO - Génération terminée: 0 fiches créées, 24 erreurs

'Generated programme: ../fiches\\Q2_2025 - Génération terminée: 0 fiches créées, 24 erreurs'

In [15]:
quantum = pd.read_excel(quantume_path)

In [16]:
quantum

,STRUCTURES,BRIGADES,NUM_IFU,NOM,ACTIVITES,PROGRAMME,ANNEE_ GESTION,TYPE_ CONTROLE
0,DME-CIII,BV1-DME-C3,00021356D,PHARMACIE NEIMA (PHARMACIE NEIMA SARL),COMMERCE DE DÉTAIL EN MAGASIN SPÉCIALISÉ DE PR...,1ER QUANTUM 2024,2021 2022 2023,VG
1,DME-CIV,BV2-DME-C4,00003877M,UNIVERSITE DE OUAGADOUGOU LIBRAIRIE UNIVERSITA...,NaN,2E QUANTUM 2024,2,VG
2,DME-CIV,BV3-DME-C4,00066918S,"IBRAIME TRAORE (CABINET MORY PRESTATIONS "" CMP"")",NaN,2E QUANTUM 2024,2,VG
3,DME-CIV,BV4-DME-C4,00048272K,ABEL BICABA,PRATIQUE MÉDICALE ET/OU DENTAIRE,1ER QUANTUM 2024,2021,VP
4,DME-CIV,BV4-DME-C4,00060978J,DRISSA SIRI,"ACTIVITÉS D'ARCHITECTURE, D'INGÉNIERIE ET AUTR...",1ER QUANTUM 2024,2021,VP
5,DME-CIV,BV4-DME-C4,00080666J,SOUNA COMPAORE/SANI,AUTRES ACTIVITÉS DE SERVICES PERSONNELS,1ER QUANTUM 2024,2023,VP
6,DME-CIV,BV4-DME-C4,00128041A,DIALENLI ROLAND TANKOANO,ACTIVITÉS JURIDIQUES,1ER QUANTUM 2024,2022,VP
7,DME-CIV,BV4-DME-C4,00132794W,VICTORIEN AIMAR SAWADOGO,ACTIVITÉS DE FORMATION PERMANENTE ET AUTRES,1ER QUANTUM 2024,2021,VP
8,DRI-C,BV-OUAGA2,00128844C,ADAMA ZEBA,ACTIVITÉS COMPTABLES ET D'AUDIT ; CONSEIL FISCAL,1ER QUANTUM 2024,2022,VP
9,DRI-C,BV-OUAGA2,00054890D,STARCOM (STARCOM SARL),AUTRES ACTIVITÉS DE SERVICES FOURNIS PRINCIPAL...,1ER QUANTUM 2024,2021 2022 2023,VG
10,DRI-C,BV-OUAGA2,00001496E,SALIFOU OUEDRAOGO (ETS OUEDRAOGO SALIFOU),COMMERCE DE GROS D'AUTRES MATÉRIAUX DE CONSTRU...,2E QUANTUM 2024,2021 2022,VG
11,DRI-C,BV-OUAGA3,00142129D,SERVICE TRAVAUX BÂTIMENT ET HYDRAULIQUE (SERV...,CONSTRUCTION DES BÂTIMENTS,1ER QUANTUM 2024,2021,VP
12,DRI-C,BV-OUAGA4,00013267F,GECIBAT SA,NaN,2E QUANTUM 2024,NaN,VG
13,DRI-C,BV-OUAGA8,00072659H,ETSS SAWADOGO & FILS NABASNOGO WEND PANGA (ES...,CONSTRUCTION ET MENUISERIE MÉTALLIQUES ; FABRI...,1ER QUANTUM 2024,2021,VP
14,DRI-C,BV-OUAGA9,00135010A,HAMED NABA (ECNAF-SERVICE),CONSTRUCTION DES BÂTIMENTS,1ER QUANTUM 2024,2023,VP
15,DRI-C,BV-OUAGA9,00149922N,ENT. QUINCAILLERIE TOUS TRAVAUX DE BATIMENT (...,AUTRES ACTIVITÉS DE SERVICES FOURNIS PRINCIPAL...,1ER QUANTUM 2024,2023,VP
16,DRI-C,BV-OUAGA9,00138126S,COGEFORE-AFRIQUE,ACTIVITES D'ETUDES DE MARCHE ET DE SONDAGE;CON...,2E QUANTUM 2024,2021 2022 2023,VG
17,DRI-CS,BV-DRI-CS,00052658S,INOUSSA SANE (ENTREPRISE SANE INOUSSA ET FRERES),CONSTRUCTION DES BÂTIMENTS,1ER QUANTUM 2024,2021 2022 2023,VG
18,DRI-CSC,BV-DRI-CSC,00005053R,PHARMACIE NADON (PHARMACIE NADON),COMMERCE DE DÉTAIL EN MAGASIN SPÉCIALISÉ DE PR...,1ER QUANTUM 2024,2022,VP
19,DRI-HBS,BV-BOBO2,00042757A,ABDOULAYE SOMBIE (STATION ORYX ACCART VILLE),COMMERCE DE DÉTAIL DE CARBURANTS,2E QUANTUM 2024,2021 2022 2023,VG
20,DRI-SO,BV-DRI-SO,00120164D,TRESORERIE REGIONALE DU SUD OUEST (TRESORERIE...,NaN,2E QUANTUM 2024,2021 2022 2023,VG
21,DME-CI,BV2-DME-CI,00004485A,DERRA KARIM,BTP,3ème quantum,2022-2022-2023,VP
22,DRI-C,BV-OUAGAVII,00022087Y,BARRY/ CISSE AÎDA,Agence de voyage,3ème quantum,"2021,2022,2023",VG
23,DRI-C,BV-OUAGAVII,00170089U,RELI INTER,Transport de carburant,3ème quantum,"2021,2022,2023",VG

In [12]:
quantum
contrib =  loader._extract_contribuables_with_exclusions(connect)

2026-04-07 17:03:10,375 - core.data_loader - INFO - Extraction contribuables
2026-04-07 17:03:12,462 - core.data_loader - INFO - Contribuables extraits: 677677/677677 après exclusions en 2.09s

In [4]:
data_dict = loader.extract_complete_oracle_data()

2026-04-06 14:55:14,269 - core.data_loader - INFO -  1.=== EXTRACTION COMPLÈTE ORACLE (Reproduction Scripts R) ===
2026-04-06 14:55:14,436 - core.data_loader - INFO - Extraction contribuables
2026-04-06 14:56:23,400 - core.data_loader - INFO - Contribuables extraits: 677675/677675 après exclusions en 68.96s
2026-04-06 14:56:23,400 - core.data_loader - INFO - Construction BD_TVA complète (reproduction R)
2026-04-06 14:56:32,286 - core.data_loader - INFO - BD_TVA construite (R-compatible): 59034 lignes en 8.88s
2026-04-06 14:56:32,286 - core.data_loader - INFO - Extraction DCF_TVA_DEDUCTION
2026-04-06 14:56:57,691 - core.data_loader - INFO - DCF_TVA_DEDUCTION extraite: 62082 lignes en 25.39s
2026-04-06 14:56:57,692 - core.data_loader - INFO - Extraction DGD complète avec nomenclature
2026-04-06 14:57:06,810 - core.data_loader - INFO - DGD extraite de la base Oracle: 38490 lignes
2026-04-06 14:57:06,810 - core.data_loader - INFO - DGD complète extraite: 38490 lignes en 9.12s
2026-04-06 14:57:06,810 - core.data_loader - INFO - Extraction programmation et contrôles
2026-04-06 14:57:08,503 - core.data_loader - INFO - Programmation extraite: 13231 lignes en 1.69s
2026-04-06 14:57:08,503 - core.data_loader - INFO - Extraction bénéfices complets
2026-04-06 15:00:30,531 - core.data_loader - INFO - Bénéfices extraits: 35136 lignes en 202.03s
2026-04-06 15:00:30,531 - core.data_loader - INFO - Extraction INSD
2026-04-06 15:00:35,741 - core.data_loader - INFO - INSD extraite: 7487 lignes en 5.20s

In [99]:
bd_tva = data_dict["bd_tva"]
bd_tva

,NUM_IFU,NOM,ANNEE_FISCAL,MONTANT_DECLARE,OP_TAXBLE_COURANTE_VENTES_PRESTATIONS_SERVICES_TRVX_IMMO_01,OP_TAXBLE_COURANTE_LIVRAISON_A_SOI_MEME_02,OP_TAXBLE_COURANTE_CESSION_IMMO_03,OP_TAXBLE_COURANTE_OPERATION_TAXABLE_TAUX_10PC_218,OP_TAXBLE_COURANTE_AUTRES_OPERATIONS_TAXABLES_04,OP_TAXBLE_MARCHE_CDE_VENTES_05,...,TVA_VTE_SERVICE_RESILIES_21,AUTRES_DEDUCTIONS_22,CREDIT_TVA_NON_REMBOURSE_23,MONTANT_TVA_PAYABLE_AVIS_CREDIT_127,MONTANT_TVA_NET_A_PAYER_25,MONTANT_TOTAL_OPERATIONS_24,CREDIT_TVA_A_REMBOURSER_26,NB_DECLARATIONS,TVA_DECEMBRE,ANNEE
0,RF1403929,SBE DEDOUGOU,2018,108000,0,0,0,0,0,0,...,0,0,0,0,108000,0,0,2,0,2018
1,RF1506336,ONTTB/BANFORA,2017,716201,3978894,0,0,0,0,0,...,0,0,0,0,716201,3978894,0,1,0,2017
2,RF1600559,Laiterie de Fada,2017,658297,0,0,0,0,0,0,...,0,0,0,0,658297,0,0,1,658297,2017
3,RF1600559,Laiterie de Fada,2018,3408061,10494386,0,0,0,0,0,...,0,0,0,0,3408061,10494386,0,6,0,2018
4,RF1609626,SANOU ABDOULAYE IFU 00018266 U,2017,77617,20850246,0,0,0,0,0,...,0,0,0,0,77617,260567855,0,1,77617,2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59029,00267818P,MADJALIA OUATTARA,2025,611107,0,0,0,0,8181561,0,...,0,0,0,0,611107,116945080,0,2,0,2025
59030,00270011L,PHARMACIE BAANI,2025,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2,0,2025
59031,00270426W,PHARMACIE ZIA,2025,0,832477,0,0,0,0,0,...,0,0,0,0,0,26426585,110316,2,0,2025
59032,00270559G,BURKINA UNDERGROUND MINING SERVICES AND SOLUTI...,2025,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2,0,2025
59033,00273202N,SYNERGIE DES TECHNOLOGIES MODERNES,2025,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,2025

In [ ]:
dcf_prog = pd.read_csv("./data/DCF_PROG_09_02_2026.csv", sep=";")
dcf_prog

In [64]:
contribuables =data_dict["contribuables"]
contribuables =contribuables[contribuables["NUM_IFU"].str.match(r"^.{9}$")]
contribuables

,ID_CONTR,NUM_IFU,NOM,NOM_MINEFID,DATE_CREATION,DATE_IMMAT,ETAT,TEL,EMAIL,CODE_FJ,...,CAPITAL,CHIF_AFFAIREPREV,ADR_CTR,NATIONALITE_CTR,FLAG_RESIDENT,NOCNSS,FLAG_EMPLOYEUR,STRUCTURES,LIBELLE_SECT_ACT,LIBELLE_GR_SECT_ACT
1,498850,RF1300002,SAWADOGO MOUMOUNI,SAWADOGO MOUMOUNI,2013-01-04 00:00:00,2013-01-04 00:00:00,ACTIF,None,None,None,...,NaN,NaN,None,None,None,None,None,None,None,None
2,498851,RF1300003,GUIGMA MAMOUDOU,GUIGMA MAMOUDOU,2013-01-04 00:00:00,2013-01-04 00:00:00,ACTIF,None,None,None,...,NaN,NaN,None,None,None,None,None,None,None,None
3,498852,RF1300004,OUEDRAOGO MAHAMADI,OUEDRAOGO MAHAMADI,2013-01-04 00:00:00,2013-01-04 00:00:00,ACTIF,None,None,None,...,NaN,NaN,None,None,None,None,None,None,None,None
4,498870,RF1300005,KORAHIRE Hadé,KORAHIRE Hadé,2013-01-04 00:00:00,2013-01-04 00:00:00,ACTIF,None,None,None,...,NaN,NaN,None,None,None,None,None,None,None,None
5,498950,RF1300015,INDIS BATIMENTS,INDIS BATIMENTS,2013-01-07 00:00:00,2013-01-07 00:00:00,ACTIF,50 35 29 31,None,None,...,NaN,NaN,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
677672,1223086,00295796R,GABIN TOUPANGA TNGUERI,GABIN TOUPANGA TNGUERI,2025-12-28 12:58:00,2025-12-28 13:58:00,ACTIF,71-22-25-59,None,43,...,0.0,0.0,OUAGADOUGOU,35,OUI,None,NON,None,AUTRES ACTIVITÉS DE SERVICES PERSONNELS,None
677673,1223090,00295797X,LARBA ABOUBACAR BILA,LARBA ABOUBACAR BILA,2025-12-28 13:05:55,2025-12-28 14:05:55,ACTIF,76-80-01-71,None,43,...,0.0,0.0,OUAGADOUGOU,35,OUI,None,NON,None,AUTRES ACTIVITÉS DE SERVICES PERSONNELS,None
677674,1223087,00295798K,ASSOCIATION ISLAMIQUE TAYBAH,ASSOCIATION ISLAMIQUE TAYBAH,2025-12-28 13:13:07,2025-12-28 14:13:07,ACTIF,75-97-40-78,None,60,...,0.0,0.0,OUAGADOUGOU,35,OUI,None,NON,None,ACTIVITÉS D'AUTRES ORGANISATIONS ASSOCIATIVES ...,None
677675,1223092,00295799F,HOUMPOUGUINI THIOMBIANO,HOUMPOUGUINI THIOMBIANO,2025-12-28 13:21:46,2025-12-28 14:21:46,ACTIF,78-87-67-92,None,43,...,0.0,0.0,OUAGADOUGOU,35,OUI,None,NON,None,AUTRES ACTIVITÉS DE SERVICES PERSONNELS,None
677676,1223093,00295800B,ASSOCIATION TALITHAKUM,ASSOCIATION TALITHAKUM,2025-12-28 14:29:40,2025-12-28 15:29:40,ACTIF,57-00-69-76,None,60,...,0.0,0.0,OUAGADOUGOU,35,OUI,None,NON,None,ACTIVITÉS D'AUTRES ORGANISATIONS ASSOCIATIVES ...,None

In [5]:
data_from_process = loader.run_extract_merge()

2026-04-06 15:03:03,086 - core.data_loader - INFO - === EXTRACTION & FUSION ===
2026-04-06 15:03:03,086 - core.data_loader - INFO -  1.=== EXTRACTION COMPLÈTE ORACLE (Reproduction Scripts R) ===
2026-04-06 15:03:03,086 - core.data_loader - INFO - Extraction contribuables
2026-04-06 15:04:04,735 - core.data_loader - INFO - Contribuables extraits: 677675/677675 après exclusions en 61.64s
2026-04-06 15:04:04,735 - core.data_loader - INFO - Construction BD_TVA complète (reproduction R)
2026-04-06 15:04:15,437 - core.data_loader - INFO - BD_TVA construite (R-compatible): 59034 lignes en 10.70s
2026-04-06 15:04:15,437 - core.data_loader - INFO - Extraction DCF_TVA_DEDUCTION
2026-04-06 15:04:39,072 - core.data_loader - INFO - DCF_TVA_DEDUCTION extraite: 62082 lignes en 23.64s
2026-04-06 15:04:39,074 - core.data_loader - INFO - Extraction DGD complète avec nomenclature
2026-04-06 15:04:48,231 - core.data_loader - INFO - DGD extraite de la base Oracle: 38490 lignes
2026-04-06 15:04:48,231 - core.data_loader - INFO - DGD complète extraite: 38490 lignes en 9.16s
2026-04-06 15:04:48,235 - core.data_loader - INFO - Extraction programmation et contrôles
2026-04-06 15:04:49,864 - core.data_loader - INFO - Programmation extraite: 13231 lignes en 1.63s
2026-04-06 15:04:49,864 - core.data_loader - INFO - Extraction bénéfices complets
2026-04-06 15:08:26,459 - core.data_loader - INFO - Bénéfices extraits: 35136 lignes en 216.59s
2026-04-06 15:08:26,459 - core.data_loader - INFO - Extraction INSD
2026-04-06 15:08:29,024 - core.data_loader - INFO - INSD extraite: 7487 lignes en 2.56s
2026-04-06 15:08:29,033 - core.data_loader - INFO - Étape d'extraction terminée en 325.95s
2026-04-06 15:08:29,033 - core.data_loader - INFO - 2.=== FUSION DES DONNÉES ===
2026-04-06 15:08:29,170 - core.data_loader - INFO - IFU invalides filtrés dans tva_deductions: 14349 lignes supprimées
2026-04-06 15:08:29,192 - core.data_loader - INFO - IFU invalides filtrés dans dgd_data: 7 lignes supprimées
2026-04-06 15:08:29,211 - core.data_loader - INFO - IFU invalides filtrés dans insd: 7 lignes supprimées
2026-04-06 15:08:29,223 - core.data_loader - INFO - Doublons (NUM_IFU_CONTRIBUABLE, ANNEE) supprimés dans insd: 70
2026-04-06 15:08:30,676 - core.data_loader - INFO - Fusion avec BD_TVA: 723673 lignes
2026-04-06 15:08:33,215 - core.data_loader - INFO - Fusion avec DCF_TVA_DEDUCTION: 736441 lignes
2026-04-06 15:08:35,832 - core.data_loader - INFO - Fusion avec DGD: 758278 lignes
2026-04-06 15:08:35,839 - core.data_loader - INFO - Doublons (NUM_IFU, NOM_MINEFID) supprimés dans programmation: 294
2026-04-06 15:08:37,469 - core.data_loader - INFO - Fusion avec Programmation|controlle: 758278 lignes
2026-04-06 15:08:39,635 - core.data_loader - INFO - Fusion avec Bénéfices: 778442 lignes
2026-04-06 15:08:42,599 - core.data_loader - INFO - Fusion avec INSD: 779046 lignes
2026-04-06 15:08:43,744 - core.data_loader - INFO - Lignes avec IFU hors contribuables supprimées: 8171
2026-04-06 15:08:44,564 - core.data_loader - INFO - Doublons (NUM_IFU, ANNEE) supprimés dans merged_data final: 18559
2026-04-06 15:09:15,478 - core.data_loader - INFO - Étape de fusion terminée en 46.44s

In [6]:
import pandas as pd
merged_data = pd.read_csv("../data/merged_data/merged_data_20260403_050838.csv",sep=",")
merged_data

,ID_CONTR,NUM_IFU,NOM_x,NOM_MINEFID,DATE_CREATION,DATE_IMMAT,ETAT,TEL,EMAIL,CODE_FJ,...,ID_TTLPRODUCTIONEXERCICE,AZ_TTLACTIFIMMOB_EXER31_12_N_BRUT,BI_CLIENTS_EXER31_12_N_NET,DN_PROVIRISQCHARGCOURTERM_EXER31_12_N_NET,CP_TTLCPTAUXPROPRESSASSIM_EXER31_12_N_NET,DD_TTLDETFINRESSASSIM_EXER31_12_N_NET,TTLPROVIRISQCHARG_ANNEEN,FONDSROULEMENT_ANNEEN,NUM_IFU_CONTRIBUABLE,NUMID
0,NaN,00000001E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,00000001E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,00000001E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,462268.0,00000001E,ZEGOMYANDE JUSTIN ROUAMBA,ZEGOMYANDE JUSTIN ROUAMBA (ETS RZF),2006-01-06,2006-01-09 00:00:00,INACTIF,70.25.08.32,NaN,55.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,455300.0,00000002H,NETCOM SA,NETCOM SA (NETCOM SA),2006-01-09,2006-01-09 00:00:00,INACTIF,50 30 02 45/50 33 22 32,NETCOM.OUAGA@NETCOM.SN,30.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
772993,1223058.0,RF2583715,KONE/TIONOU ROSE,KONE/TIONOU ROSE,2025-12-27 11:18:08,2025-12-27 00:00:00,ACTIF,74779411,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
772994,1223059.0,RF2583716,SAWADOGO SIDIKI,SAWADOGO SIDIKI,2025-12-27 11:22:24,2025-12-27 00:00:00,ACTIF,74779411,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
772995,1223075.0,RF2583717,KAMBIRE COLLETTE,KAMBIRE COLLETTE,2025-12-28 09:13:54,2025-12-28 00:00:00,ACTIF,70254319,NaN,43,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
772996,1223078.0,RF2583718,NANA DIEUDONNE,NANA DIEUDONNE,2025-12-28 11:39:08,NaN,ACTIF,74 38 14 45,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
772997,1223079.0,RF2583719,NIKIEMA BINTA,NIKIEMA BINTA,2025-12-28 11:46:05,NaN,ACTIF,74 38 14 45,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
merged_data["DATE_DERNIERE_VG"].isnull().sum()

np.int64(731800)

In [9]:
data_from_process["DATE_DERNIERE_VG"].isnull().sum()

np.int64(711424)

In [ ]:
import pandas as pd
data_dict["contribuables"]["DATE_IMMAT"] = pd.to_datetime(data_dict["contribuables"]["DATE_IMMAT"])

In [23]:
data_dict["programmation"]["DATE_IMMAT"] = pd.to_datetime(data_dict["programmation"]["DATE_IMMAT"])

In [38]:
import pandas as pd
contribuable_controle = pd.merge(
               data_dict["contribuables"],
                data_dict["programmation"],
                on=["NUM_IFU","NOM_MINEFID"],
                how="left",
            )

In [24]:
data_from_process["BI_CLIENTS_EXER31_12_N_NET"].isnull().sum()

np.int64(745479)

In [5]:
r_38 = computer.run(data=data_from_process,quantume_name="Q2_20262",indicateurs=[37,38,39,40,46,47,49,57,58])

2026-04-05 08:37:01,862 - core.risk_compute - INFO - === DÉMARRAGE PROCESSUS: RECUPERATION & CALCUL DES RISQUES ===
2026-04-05 08:37:02,706 - core.risk_compute - INFO - Données chargées et mergées avec succès: 752314 lignes
2026-04-05 08:37:02,706 - core.risk_compute - INFO - === CALCUL DE 9 INDICATEURS ===
2026-04-05 08:37:02,707 - core.risk_compute - INFO - 1.avant filtre: 752314 lignes
2026-04-05 08:37:02,707 - core.risk_compute - INFO - 2.apres filtre: 752314 lignes
2026-04-05 08:37:03,068 - core.risk_compute - INFO - Colonnes de base initialisées: 10 colonnes
2026-04-05 08:37:03,069 - core.risk_compute - INFO - === START: Groupe Controle (IND 15A, 15B, 30) ===
2026-04-05 08:37:03,070 - indicateurs.controle_indicators - INFO - === START: Groupe Controle (IND 15A, 15B, 16, 30) ===
2026-04-05 08:37:03,070 - indicateurs.controle_indicators - INFO - Start.compute ===>IND15
2026-04-05 08:37:03,226 - indicateurs.controle_indicators - INFO - END.compute ===>IND15
2026-04-05 08:37:03,227 - indicateurs.controle_indicators - INFO - Start.compute ===>IND16
2026-04-05 08:37:03,358 - indicateurs.controle_indicators - INFO - END.compute ===>IND16
2026-04-05 08:37:03,359 - indicateurs.controle_indicators - INFO - Start.compute ===>IND30
2026-04-05 08:37:06,765 - indicateurs.controle_indicators - INFO - END.compute ===>IND30
2026-04-05 08:37:06,887 - indicateurs.controle_indicators - INFO - === END: Groupe Controle ===
2026-04-05 08:37:06,922 - core.risk_compute - INFO - === END: Groupe Controle ===
2026-04-05 08:37:06,923 - core.risk_compute - INFO - === START: Groupe TVA (IND 1, 2, 8, 10, 12, 13, 14) ===
2026-04-05 08:37:06,924 - core.risk_compute - INFO - === END: Groupe TVA ===
2026-04-05 08:37:06,924 - core.risk_compute - INFO - === START: Groupe Import/Export (IND 3, 4, 5, 7) ===
2026-04-05 08:37:06,925 - core.risk_compute - INFO - === END: Groupe Import/Export ===
2026-04-05 08:37:06,925 - core.risk_compute - INFO - === START: Groupe Comptabilite (IND 6, 9, 20, 21, 23, 24, 25, 26, 27, 29, 32, 33, 34) ===
2026-04-05 08:37:06,926 - core.risk_compute - INFO - === END: Groupe Comptabilite ===
2026-04-05 08:37:06,926 - core.risk_compute - INFO - === START: Groupe Avance (IND 37, 38, 39, 46, 47, 49, 57, 58) ===
2026-04-05 08:37:06,927 - indicateurs.advanced_indicators - INFO - Start.compute ===>IND37
2026-04-05 08:37:10,374 - indicateurs.advanced_indicators - INFO - END.compute ===>IND37
2026-04-05 08:37:10,556 - indicateurs.advanced_indicators - INFO - Start.compute ===>IND38
2026-04-05 08:37:14,399 - indicateurs.advanced_indicators - INFO - END.compute ===>IND38
2026-04-05 08:37:14,566 - indicateurs.advanced_indicators - INFO - Start.compute ===>IND39
2026-04-05 08:37:18,686 - indicateurs.advanced_indicators - INFO - END.compute ===>IND39
2026-04-05 08:37:18,865 - indicateurs.advanced_indicators - INFO - Start.compute ===>IND46
2026-04-05 08:37:18,866 - indicateurs.advanced_indicators - INFO - Start.compute ===>IND47
2026-04-05 08:37:18,867 - indicateurs.advanced_indicators - INFO - Start.compute ===>IND49
2026-04-05 08:37:22,045 - indicateurs.advanced_indicators - INFO - END.compute ===>IND49
2026-04-05 08:37:22,142 - indicateurs.advanced_indicators - INFO - Start.compute ===>IND57
2026-04-05 08:37:24,032 - indicateurs.advanced_indicators - INFO - END.compute ===>IND57
2026-04-05 08:37:24,216 - indicateurs.advanced_indicators - INFO - Start.compute ===>IND58
2026-04-05 08:37:26,690 - indicateurs.advanced_indicators - INFO - END.compute ===>IND58
2026-04-05 08:37:26,868 - core.risk_compute - INFO - === END: Groupe Avance ===
2026-04-05 08:37:26,868 - core.risk_compute - INFO - Calcul de tous les indicateurs terminé
2026-04-05 08:37:29,488 - core.risk_compute - INFO - === ANALYSE TERMINÉE EN 25.11s ===
2026-04-05 08:37:29,488 - core.risk_compute - INFO - Résultats sauvegardés dans: ../data/risk_contribuables/Q2_20262.csv

In [ ]:
r = computer.run(data=data_from_process,quantume_name="Q2_2026",indicateurs=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37])

2026-04-03 07:29:47,865 - core.risk_compute - INFO - === DÉMARRAGE PROCESSUS: RECUPERATION & CALCUL DES RISQUES ===
2026-04-03 07:29:48,750 - core.risk_compute - INFO - Données chargées et mergées avec succès: 752256 lignes
2026-04-03 07:29:48,750 - core.risk_compute - INFO - === CALCUL DE 37 INDICATEURS ===
2026-04-03 07:29:48,750 - core.risk_compute - INFO - 1.avant filtre: 752256 lignes
2026-04-03 07:29:48,750 - core.risk_compute - INFO - 2.apres filtre: 752256 lignes
2026-04-03 07:29:49,101 - core.risk_compute - INFO - Colonnes de base initialisées: 10 colonnes
2026-04-03 07:29:49,101 - core.risk_compute - INFO - === START: Groupe Controle (IND 15A, 15B, 30) ===
2026-04-03 07:29:49,101 - indicateurs.controle_indicators - INFO - === START: Groupe Controle (IND 15A, 15B, 16, 30) ===
2026-04-03 07:29:49,101 - indicateurs.controle_indicators - INFO - Start.compute ===>IND15
2026-04-03 07:29:49,251 - indicateurs.controle_indicators - INFO - END.compute ===>IND15
2026-04-03 07:29:49,251 - indicateurs.controle_indicators - INFO - Start.compute ===>IND16
2026-04-03 07:29:49,387 - indicateurs.controle_indicators - INFO - END.compute ===>IND16
2026-04-03 07:29:49,387 - indicateurs.controle_indicators - INFO - Start.compute ===>IND30
2026-04-03 07:29:52,698 - indicateurs.controle_indicators - INFO - END.compute ===>IND30
2026-04-03 07:29:52,885 - indicateurs.controle_indicators - INFO - === END: Groupe Controle ===
2026-04-03 07:29:52,923 - core.risk_compute - INFO - === END: Groupe Controle ===
2026-04-03 07:29:52,923 - core.risk_compute - INFO - === START: Groupe TVA (IND 1, 2, 8, 10, 12, 13, 14) ===
2026-04-03 07:29:52,931 - indicateurs.tva_indicators - INFO - Start.compute ===>IND1
2026-04-03 07:29:52,956 - indicateurs.tva_indicators - INFO - End.compute ===>IND1
2026-04-03 07:29:52,956 - indicateurs.tva_indicators - INFO - Start.compute ===>IND2
2026-04-03 07:29:52,989 - indicateurs.tva_indicators - INFO - END.compute ===>IND2
2026-04-03 07:29:52,992 - indicateurs.tva_indicators - INFO - Start.compute ===>IND8
2026-04-03 07:29:53,021 - indicateurs.tva_indicators - INFO - END.compute ===>IND8
2026-04-03 07:29:53,022 - indicateurs.tva_indicators - INFO - Start.compute ===>IND10
2026-04-03 07:29:53,050 - indicateurs.tva_indicators - INFO - END.compute ===>IND10
2026-04-03 07:29:53,051 - indicateurs.tva_indicators - INFO - Start.compute ===>IND12
2026-04-03 07:29:53,070 - indicateurs.tva_indicators - INFO - END.compute ===>IND12
2026-04-03 07:29:53,081 - indicateurs.tva_indicators - INFO - Start.compute ===>IND13
2026-04-03 07:29:53,200 - indicateurs.tva_indicators - INFO - END.compute ===>IND13
2026-04-03 07:29:53,200 - indicateurs.tva_indicators - INFO - Start.compute ===>IND14
2026-04-03 07:29:53,242 - indicateurs.tva_indicators - INFO - END.compute ===>IND14
2026-04-03 07:29:53,243 - core.risk_compute - INFO - === END: Groupe TVA ===
2026-04-03 07:29:53,243 - core.risk_compute - INFO - === START: Groupe Import/Export (IND 3, 4, 5, 7) ===
2026-04-03 07:29:53,245 - indicateurs.import_export_indicators - INFO - Start.compute ===>IND3
2026-04-03 07:29:53,614 - indicateurs.import_export_indicators - INFO - END.compute ===>IND3
2026-04-03 07:29:53,630 - indicateurs.import_export_indicators - INFO - Start.compute ===>IND4
2026-04-03 07:29:53,814 - indicateurs.import_export_indicators - INFO - END.compute ===>IND4
2026-04-03 07:29:53,831 - indicateurs.import_export_indicators - INFO - Start.compute ===>IND5
2026-04-03 07:29:53,964 - indicateurs.import_export_indicators - INFO - END.compute ===>IND5
2026-04-03 07:29:53,981 - indicateurs.import_export_indicators - INFO - Start.compute ===>IND7
2026-04-03 07:29:53,981 - indicateurs.import_export_indicators - INFO - END.compute ===>IND7
2026-04-03 07:29:53,996 - core.risk_compute - INFO - === END: Groupe Import/Export ===
2026-04-03 07:29:53,997 - core.risk_compute - INFO - === START: Groupe Comptabilite (IND 6, 9, 20, 21, 23, 24, 25, 26, 27, 29, 32, 33, 34) ===
2026-04-03 07:29:53,997 - indicateurs.comptabilite_indicators - INFO - Start.compute ===>IND9
2026-04-03 07:29:53,999 - indicateurs.comptabilite_indicators - INFO - Start.compute ===>IND6
2026-04-03 07:29:55,363 - indicateurs.comptabilite_indicators - INFO - END.compute ===>IND6
2026-04-03 07:29:55,446 - indicateurs.comptabilite_indicators - INFO - Start.compute ===>IND20
2026-04-03 07:29:56,914 - indicateurs.comptabilite_indicators - INFO - END.compute ===>IND20
2026-04-03 07:29:56,997 - indicateurs.comptabilite_indicators - INFO - Start.compute ===>IND21
2026-04-03 07:29:56,997 - indicateurs.comptabilite_indicators - INFO - Start.compute ===>IND23
2026-04-03 07:29:56,997 - indicateurs.comptabilite_indicators - INFO - Start.compute ===>IND24
2026-04-03 07:29:58,094 - indicateurs.comptabilite_indicators - INFO - END.compute ===>IND24
2026-04-03 07:29:58,244 - indicateurs.comptabilite_indicators - INFO - Start.compute ===>IND25
2026-04-03 07:29:59,398 - indicateurs.comptabilite_indicators - INFO - END.compute ===>IND25
2026-04-03 07:29:59,553 - indicateurs.comptabilite_indicators - INFO - Start.compute ===>IND26
2026-04-03 07:30:00,692 - indicateurs.comptabilite_indicators - INFO - END.compute ===>IND26
2026-04-03 07:30:00,825 - indicateurs.comptabilite_indicators - INFO - Start.compute ===>IND27
2026-04-03 07:30:00,825 - indicateurs.comptabilite_indicators - INFO - Start.compute ===>IND29
2026-04-03 07:30:00,825 - indicateurs.comptabilite_indicators - INFO - Start.compute ===>IND32
2026-04-03 07:30:04,502 - indicateurs.comptabilite_indicators - INFO - END.compute ===>IND32
2026-04-03 07:30:04,750 - indicateurs.comptabilite_indicators - INFO - Start.compute ===>IND33
2026-04-03 07:30:08,726 - indicateurs.comptabilite_indicators - INFO - END.compute ===>IND33
2026-04-03 07:30:08,979 - indicateurs.comptabilite_indicators - INFO - Start.compute ===>IND34
2026-04-03 07:30:12,487 - indicateurs.comptabilite_indicators - INFO - END.compute ===>IND34
2026-04-03 07:30:12,722 - core.risk_compute - INFO - === END: Groupe Comptabilite ===
2026-04-03 07:30:12,722 - core.risk_compute - INFO - === START: Groupe Avance (IND 37, 38, 39, 46, 47, 49, 57, 58) ===
2026-04-03 07:30:12,722 - indicateurs.advanced_indicators - INFO - Start.compute ===>IND37
2026-04-03 07:30:16,645 - indicateurs.advanced_indicators - INFO - END.compute ===>IND37
2026-04-03 07:30:16,883 - core.risk_compute - INFO - === END: Groupe Avance ===
2026-04-03 07:30:16,883 - core.risk_compute - INFO - Calcul de tous les indicateurs terminé
2026-04-03 07:30:26,110 - core.risk_compute - INFO - === ANALYSE TERMINÉE EN 29.12s ===
2026-04-03 07:30:26,110 - core.risk_compute - INFO - Résultats sauvegardés dans: ../data/risk_contribuables/Q2_2026

In [56]:
data_from_process["DATE_DERNIERE_VG"].isnull().sum()

np.int64(711422)

In [55]:
m= (data_from_process["DATE_DERNIERE_VG"]< pd.to_datetime("2026-12-31")) #& (data_from_process["DATE_DERNIERE_VG"]> pd.to_datetime("2023-01-01"))
md= data_from_process[m]
md

,ID_CONTR,NUM_IFU,NOM_x,NOM_MINEFID,DATE_CREATION,DATE_IMMAT,ETAT,TEL,EMAIL,CODE_FJ,...,ID_TTLPRODUCTIONEXERCICE,AZ_TTLACTIFIMMOB_EXER31_12_N_BRUT,BI_CLIENTS_EXER31_12_N_NET,DN_PROVIRISQCHARGCOURTERM_EXER31_12_N_NET,CP_TTLCPTAUXPROPRESSASSIM_EXER31_12_N_NET,DD_TTLDETFINRESSASSIM_EXER31_12_N_NET,TTLPROVIRISQCHARG_ANNEEN,FONDSROULEMENT_ANNEEN,NUM_IFU_CONTRIBUABLE,NUMID
151,455302.0,00000004U,SCIENCES CONSULTING & TRADE,SCIENCES CONSULTING & TRADE (SCT),2006-01-12,2006-01-13 00:00:00,ACTIF,78-82-30-36,None,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
152,455302.0,00000004U,SCIENCES CONSULTING & TRADE,SCIENCES CONSULTING & TRADE (SCT),2006-01-12,2006-01-13 00:00:00,ACTIF,78-82-30-36,None,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
153,455302.0,00000004U,SCIENCES CONSULTING & TRADE,SCIENCES CONSULTING & TRADE (SCT),2006-01-12,2006-01-13 00:00:00,ACTIF,78-82-30-36,None,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
154,455302.0,00000004U,SCIENCES CONSULTING & TRADE,SCIENCES CONSULTING & TRADE (SCT),2006-01-12,2006-01-13 00:00:00,ACTIF,78-82-30-36,None,20,...,1024.0,45810218.0,11687341.0,0.0,53801020.0,0.0,0.0,53801020.0,00000004U,OUA2001B2694-2022
155,455302.0,00000004U,SCIENCES CONSULTING & TRADE,SCIENCES CONSULTING & TRADE (SCT),2006-01-12,2006-01-13 00:00:00,ACTIF,78-82-30-36,None,20,...,17633.0,45810218.0,93608461.0,0.0,38200483.0,0.0,0.0,38200483.0,00000004U,OUA2005M2133-2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
403709,584330.0,RF1406842,Lycée pour la Promotion des Jeunes/FONDACIO,Lycée pour la Promotion des Jeunes/FONDACIO (F...,2014-11-10,2014-11-10 00:00:00,ACTIF,None,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
411171,597482.0,RF1506064,KOUNA SARL,KOUNA SARL,2015-04-30,2015-04-30 00:00:00,ACTIF,None,None,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
424452,621416.0,RF1606215,COLLEGE PRIVE FINANDE/SIDERADOUGOU,COLLEGE PRIVE FINANDE/SIDERADOUGOU,2016-04-08,2016-04-08 00:00:00,ACTIF,None,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
456470,681373.0,RF1722021,Traoré/Diallo Aminata,Traoré/Diallo Aminata,2017-11-15,2017-11-15 00:00:00,ACTIF,None,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
461582,689545.0,RF1802246,ZONGO ISSA (BOULANGERIE YASCO),ZONGO ISSA (BOULANGERIE YASCO),2018-01-25,2018-01-25 00:00:00,ACTIF,79 11 81 39,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
r_data = computer.run(data=data_from_process,quantume_name="Q3_2026")

2026-04-06 15:15:19,225 - core.risk_compute - INFO - === DÉMARRAGE PROCESSUS: RECUPERATION & CALCUL DES RISQUES ===
2026-04-06 15:15:20,528 - core.risk_compute - INFO - Données chargées et mergées avec succès: 752316 lignes
2026-04-06 15:15:20,528 - core.risk_compute - INFO - === CALCUL DE 32 INDICATEURS ===
2026-04-06 15:15:20,538 - core.risk_compute - INFO - 1.avant filtre: 752316 lignes
2026-04-06 15:15:20,538 - core.risk_compute - INFO - 2.apres filtre: 752316 lignes
2026-04-06 15:15:21,013 - core.risk_compute - INFO - Colonnes de base initialisées: 10 colonnes
2026-04-06 15:15:21,013 - core.risk_compute - INFO - === START: Groupe Controle (IND 15A, 15B, 30) ===
2026-04-06 15:15:21,013 - indicateurs.controle_indicators - INFO - === START: Groupe Controle (IND 15A, 15B, 16, 30) ===
2026-04-06 15:15:21,013 - indicateurs.controle_indicators - INFO - Start.compute ===>IND15
2026-04-06 15:15:21,235 - indicateurs.controle_indicators - INFO - END.compute ===>IND15
2026-04-06 15:15:21,235 - indicateurs.controle_indicators - INFO - Start.compute ===>IND16
2026-04-06 15:15:21,446 - indicateurs.controle_indicators - INFO - END.compute ===>IND16
2026-04-06 15:15:21,446 - indicateurs.controle_indicators - INFO - Start.compute ===>IND30
2026-04-06 15:15:25,702 - indicateurs.controle_indicators - INFO - END.compute ===>IND30
2026-04-06 15:15:25,916 - indicateurs.controle_indicators - INFO - === END: Groupe Controle ===
2026-04-06 15:15:25,963 - core.risk_compute - INFO - === END: Groupe Controle ===
2026-04-06 15:15:25,963 - core.risk_compute - INFO - === START: Groupe TVA (IND 1, 2, 8, 10, 12, 13, 14) ===
2026-04-06 15:15:25,972 - indicateurs.tva_indicators - INFO - Start.compute ===>IND1
2026-04-06 15:15:26,011 - indicateurs.tva_indicators - INFO - End.compute ===>IND1
2026-04-06 15:15:26,018 - indicateurs.tva_indicators - INFO - Start.compute ===>IND2
2026-04-06 15:15:26,058 - indicateurs.tva_indicators - INFO - END.compute ===>IND2
2026-04-06 15:15:26,061 - indicateurs.tva_indicators - INFO - Start.compute ===>IND8
2026-04-06 15:15:26,095 - indicateurs.tva_indicators - INFO - END.compute ===>IND8
2026-04-06 15:15:26,095 - indicateurs.tva_indicators - INFO - Start.compute ===>IND10
2026-04-06 15:15:26,136 - indicateurs.tva_indicators - INFO - END.compute ===>IND10
2026-04-06 15:15:26,137 - indicateurs.tva_indicators - INFO - Start.compute ===>IND12
2026-04-06 15:15:26,178 - indicateurs.tva_indicators - INFO - END.compute ===>IND12
2026-04-06 15:15:26,178 - indicateurs.tva_indicators - INFO - Start.compute ===>IND13
2026-04-06 15:15:26,344 - indicateurs.tva_indicators - INFO - END.compute ===>IND13
2026-04-06 15:15:26,344 - indicateurs.tva_indicators - INFO - Start.compute ===>IND14
2026-04-06 15:15:26,390 - indicateurs.tva_indicators - INFO - END.compute ===>IND14
2026-04-06 15:15:26,393 - core.risk_compute - INFO - === END: Groupe TVA ===
2026-04-06 15:15:26,394 - core.risk_compute - INFO - === START: Groupe Import/Export (IND 3, 4, 5, 7) ===
2026-04-06 15:15:26,397 - indicateurs.import_export_indicators - INFO - Start.compute ===>IND3
2026-04-06 15:15:26,956 - indicateurs.import_export_indicators - INFO - END.compute ===>IND3
2026-04-06 15:15:26,965 - indicateurs.import_export_indicators - INFO - Start.compute ===>IND4
2026-04-06 15:15:27,234 - indicateurs.import_export_indicators - INFO - END.compute ===>IND4
2026-04-06 15:15:27,240 - indicateurs.import_export_indicators - INFO - Start.compute ===>IND5
2026-04-06 15:15:27,418 - indicateurs.import_export_indicators - INFO - END.compute ===>IND5
2026-04-06 15:15:27,423 - indicateurs.import_export_indicators - INFO - Start.compute ===>IND7
2026-04-06 15:15:27,440 - indicateurs.import_export_indicators - INFO - END.compute ===>IND7
2026-04-06 15:15:27,440 - core.risk_compute - INFO - === END: Groupe Import/Export ===
2026-04-06 15:15:27,440 - core.risk_compute - INFO - === START: Groupe Comptabilite (IND 6, 9, 20, 21, 23, 24, 25, 26, 27, 29, 32, 33, 34) ===
2026-04-06 15:15:27,440 - indicateurs.comptabilite_indicators - INFO - Start.compute ===>IND9
2026-04-06 15:15:27,448 - indicateurs.comptabilite_indicators - INFO - Start.compute ===>IND6
2026-04-06 15:15:29,307 - indicateurs.comptabilite_indicators - INFO - END.compute ===>IND6
2026-04-06 15:15:29,393 - indicateurs.comptabilite_indicators - INFO - Start.compute ===>IND20
2026-04-06 15:15:31,439 - indicateurs.comptabilite_indicators - INFO - END.compute ===>IND20
2026-04-06 15:15:31,537 - indicateurs.comptabilite_indicators - INFO - Start.compute ===>IND21
2026-04-06 15:15:31,537 - indicateurs.comptabilite_indicators - INFO - Start.compute ===>IND23
2026-04-06 15:15:31,537 - indicateurs.comptabilite_indicators - INFO - Start.compute ===>IND24
2026-04-06 15:15:33,003 - indicateurs.comptabilite_indicators - INFO - END.compute ===>IND24
2026-04-06 15:15:33,203 - indicateurs.comptabilite_indicators - INFO - Start.compute ===>IND25
2026-04-06 15:15:34,745 - indicateurs.comptabilite_indicators - INFO - END.compute ===>IND25
2026-04-06 15:15:34,920 - indicateurs.comptabilite_indicators - INFO - Start.compute ===>IND26
2026-04-06 15:15:36,267 - indicateurs.comptabilite_indicators - INFO - END.compute ===>IND26
2026-04-06 15:15:36,432 - indicateurs.comptabilite_indicators - INFO - Start.compute ===>IND27
2026-04-06 15:15:36,436 - indicateurs.comptabilite_indicators - INFO - Start.compute ===>IND29
2026-04-06 15:15:36,442 - indicateurs.comptabilite_indicators - INFO - Start.compute ===>IND32
2026-04-06 15:15:41,131 - indicateurs.comptabilite_indicators - INFO - END.compute ===>IND32
2026-04-06 15:15:41,414 - indicateurs.comptabilite_indicators - INFO - Start.compute ===>IND33
2026-04-06 15:15:46,595 - indicateurs.comptabilite_indicators - INFO - END.compute ===>IND33
2026-04-06 15:15:46,885 - indicateurs.comptabilite_indicators - INFO - Start.compute ===>IND34
2026-04-06 15:15:51,624 - indicateurs.comptabilite_indicators - INFO - END.compute ===>IND34
2026-04-06 15:15:51,908 - core.risk_compute - INFO - === END: Groupe Comptabilite ===
2026-04-06 15:15:51,908 - core.risk_compute - INFO - === START: Groupe Avance (IND 37, 38, 39, 46, 47, 49, 57, 58) ===
2026-04-06 15:15:51,908 - indicateurs.advanced_indicators - INFO - Start.compute ===>IND37
2026-04-06 15:15:57,283 - indicateurs.advanced_indicators - INFO - END.compute ===>IND37
2026-04-06 15:15:57,596 - indicateurs.advanced_indicators - INFO - Start.compute ===>IND38
2026-04-06 15:16:04,767 - indicateurs.advanced_indicators - INFO - END.compute ===>IND38
2026-04-06 15:16:05,211 - indicateurs.advanced_indicators - INFO - Start.compute ===>IND39
2026-04-06 15:16:15,666 - indicateurs.advanced_indicators - INFO - END.compute ===>IND39
2026-04-06 15:16:16,025 - indicateurs.advanced_indicators - INFO - Start.compute ===>IND46
2026-04-06 15:16:16,025 - indicateurs.advanced_indicators - INFO - Start.compute ===>IND47
2026-04-06 15:16:16,025 - indicateurs.advanced_indicators - INFO - Start.compute ===>IND49
2026-04-06 15:16:20,935 - indicateurs.advanced_indicators - INFO - END.compute ===>IND49
2026-04-06 15:16:21,174 - indicateurs.advanced_indicators - INFO - Start.compute ===>IND57
2026-04-06 15:16:24,441 - indicateurs.advanced_indicators - INFO - END.compute ===>IND57
2026-04-06 15:16:24,749 - indicateurs.advanced_indicators - INFO - Start.compute ===>IND58
2026-04-06 15:16:28,834 - indicateurs.advanced_indicators - INFO - END.compute ===>IND58
2026-04-06 15:16:29,166 - core.risk_compute - INFO - === END: Groupe Avance ===
2026-04-06 15:16:29,167 - core.risk_compute - INFO - Calcul de tous les indicateurs terminé
2026-04-06 15:16:29,717 - core.risk_compute - INFO - === ANALYSE TERMINÉE EN 70.10s ===
2026-04-06 15:16:29,730 - core.risk_compute - INFO - Résultats sauvegardés dans: ../data/risk_contribuables/Q3_2026.csv

In [85]:
import pandas as pd
risk_ind1 = pd.read_csv("../data/risk_contribuables/Q3_2026.csv",sep=";")
risk_ind1

,NUM_IFU,NOM_MINEFID,ETAT,CODE_SECT_ACT,CODE_REG_FISC,STRUCTURES,DATE_DERNIERE_VG,DATE_DERNIERE_VP,DATE_DERNIERE_AVIS,ANNEE,...,RISQUE_IND_32,RISQUE_IND_33,RISQUE_IND_34,RISQUE_IND_37,RATIO_IND_37,RISQUE_IND_38,RISQUE_IND_39,RISQUE_IND_49,RISQUE_IND_57,RISQUE_IND_58
0,00000001E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023.0,...,vert,vert,vert,vert,0.0,vert,vert,Non disponible,Non disponible,Non disponible
1,00000001E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0,...,vert,vert,vert,vert,0.0,vert,vert,Non disponible,Non disponible,Non disponible
2,00000001E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025.0,...,vert,vert,vert,vert,0.0,vert,vert,Non disponible,Non disponible,Non disponible
3,00000001E,ZEGOMYANDE JUSTIN ROUAMBA (ETS RZF),INACTIF,5226.0,RN,DME/CENTRE III,NaN,NaN,NaN,NaN,...,vert,vert,vert,vert,0.0,vert,vert,Non disponible,Non disponible,Non disponible
4,00000002H,NETCOM SA (NETCOM SA),INACTIF,7210.0,RN,DME/CENTRE III,NaN,NaN,NaN,2017.0,...,vert,vert,vert,vert,0.0,vert,vert,Non disponible,Non disponible,Non disponible
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
752309,RF2583715,KONE/TIONOU ROSE,ACTIF,9304.0,ND,NaN,NaN,NaN,NaN,NaN,...,vert,vert,vert,vert,0.0,vert,vert,Non disponible,Non disponible,Non disponible
752310,RF2583716,SAWADOGO SIDIKI,ACTIF,9304.0,ND,NaN,NaN,NaN,NaN,NaN,...,vert,vert,vert,vert,0.0,vert,vert,Non disponible,Non disponible,Non disponible
752311,RF2583717,KAMBIRE COLLETTE,ACTIF,8511.0,ND,NaN,NaN,NaN,NaN,NaN,...,vert,vert,vert,vert,0.0,vert,vert,Non disponible,Non disponible,Non disponible
752312,RF2583718,NANA DIEUDONNE,ACTIF,5246.0,ND,NaN,NaN,NaN,NaN,NaN,...,vert,vert,vert,vert,0.0,vert,vert,Non disponible,Non disponible,Non disponible
752313,RF2583719,NIKIEMA BINTA,ACTIF,5246.0,ND,NaN,NaN,NaN,NaN,NaN,...,vert,vert,vert,vert,0.0,vert,vert,Non disponible,Non disponible,Non disponible

In [86]:
risk_ind1["DATE_DERNIERE_VG"].isnull().sum()

np.int64(711422)

In [18]:
risk_ind1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 752314 entries, 0 to 752313
Data columns (total 72 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   NUM_IFU             752314 non-null  object
 1   NOM_MINEFID         658280 non-null  object
 2   ETAT                712781 non-null  object
 3   CODE_SECT_ACT       498974 non-null  float64
 4   CODE_REG_FISC       629986 non-null  object
 5   STRUCTURES          326097 non-null  object
 6   DATE_DERNIERE_VG    40892 non-null   object
 7   DATE_DERNIERE_VP    22306 non-null   object
 8   DATE_DERNIERE_AVIS  48145 non-null   object
 9   ANNEE               86070 non-null   float64
 10  RISQUE_IND_15_A     752314 non-null  object
 11  RISQUE_IND_15_B     752314 non-null  object
 12  RISQUE_IND_16       752314 non-null  object
 13  RISQUE_IND_30       752314 non-null  object
 14  RISQUE_IND_1        752314 non-null  object
 15  GAP_IND_1           752314 non-null  float64
 16  SCORE_IND_1         752314 non-null  int64
 17  RISQUE_IND_2        752314 non-null  object
 18  GAP_IND_2           752314 non-null  float64
 19  SCORE_IND_2         752314 non-null  int64
 20  RISQUE_IND_8        752314 non-null  object
 21  GAP_IND_8           752314 non-null  float64
 22  SCORE_IND_8         752314 non-null  int64
 23  RISQUE_IND_10       752314 non-null  object
 24  GAP_IND_10          752314 non-null  float64
 25  SCORE_IND_10        752314 non-null  int64
 26  RISQUE_IND_12       752314 non-null  object
 27  GAP_IND_12          752314 non-null  float64
 28  SCORE_IND_12        752314 non-null  int64
 29  RISQUE_IND_13       752314 non-null  object
 30  GAP_IND_13          752314 non-null  float64
 31  SCORE_IND_13        752314 non-null  int64
 32  RISQUE_IND_14       752314 non-null  object
 33  RISQUE_IND_3        752314 non-null  object
 34  RISQUE_IND_4        752314 non-null  object
 35  GAP_IND_4           752314 non-null  float64
 36  SCORE_IND_4         752314 non-null  int64
 37  RISQUE_IND_5        752314 non-null  object
 38  GAP_IND_5           752314 non-null  float64
 39  SCORE_IND_5         752314 non-null  int64
 40  RISQUE_IND_7_A      752314 non-null  object
 41  RISQUE_IND_7_B      752314 non-null  object
 42  RISQUE_IND_9        752314 non-null  object
 43  RISQUE_IND_6        752314 non-null  object
 44  GAP_IND_6           752314 non-null  float64
 45  SCORE_IND_6         752314 non-null  int64
 46  RISQUE_IND_20       752314 non-null  object
 47  GAP_IND_20          752314 non-null  float64
 48  SCORE_IND_20        752314 non-null  int64
 49  RISQUE_IND_21       752314 non-null  object
 50  RISQUE_IND_23       752314 non-null  object
 51  RISQUE_IND_24       752314 non-null  object
 52  GAP_IND_24          752314 non-null  float64
 53  SCORE_IND_24        752314 non-null  int64
 54  RISQUE_IND_25       752314 non-null  object
 55  GAP_IND_25          752314 non-null  float64
 56  SCORE_IND_25        752314 non-null  int64
 57  RISQUE_IND_26       752314 non-null  object
 58  GAP_IND_26          752314 non-null  float64
 59  SCORE_IND_26        752314 non-null  int64
 60  RISQUE_IND_27       752314 non-null  object
 61  RISQUE_IND_29       752314 non-null  object
 62  RISQUE_IND_32       752314 non-null  object
 63  RISQUE_IND_33       752314 non-null  object
 64  RISQUE_IND_34       752314 non-null  object
 65  RISQUE_IND_37       752314 non-null  object
 66  RATIO_IND_37        752314 non-null  float64
 67  RISQUE_IND_38       752314 non-null  object
 68  RISQUE_IND_39       752314 non-null  object
 69  RISQUE_IND_49       752314 non-null  object
 70  RISQUE_IND_57       752314 non-null  object
 71  RISQUE_IND_58       752314 non-null  object
dtypes: float64(16), int64(13), object(43)
memory usage: 413.3+ MB

In [32]:
m = (risk_ind1["RISQUE_IND_15_A"]=="rouge") & (risk_ind1["RISQUE_IND_15_B"]=="rouge")
filter_risk = risk_ind1[m]

In [34]:
filter_risk.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3930 entries, 134 to 199443
Data columns (total 72 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   NUM_IFU             3930 non-null   object
 1   NOM_MINEFID         3930 non-null   object
 2   ETAT                3930 non-null   object
 3   CODE_SECT_ACT       3930 non-null   float64
 4   CODE_REG_FISC       3930 non-null   object
 5   STRUCTURES          3930 non-null   object
 6   DATE_DERNIERE_VG    3930 non-null   object
 7   DATE_DERNIERE_VP    3930 non-null   object
 8   DATE_DERNIERE_AVIS  3930 non-null   object
 9   ANNEE               3905 non-null   float64
 10  RISQUE_IND_15_A     3930 non-null   object
 11  RISQUE_IND_15_B     3930 non-null   object
 12  RISQUE_IND_16       3930 non-null   object
 13  RISQUE_IND_30       3930 non-null   object
 14  RISQUE_IND_1        3930 non-null   object
 15  GAP_IND_1           3930 non-null   float64
 16  SCORE_IND_1         3930 non-null   int64
 17  RISQUE_IND_2        3930 non-null   object
 18  GAP_IND_2           3930 non-null   float64
 19  SCORE_IND_2         3930 non-null   int64
 20  RISQUE_IND_8        3930 non-null   object
 21  GAP_IND_8           3930 non-null   float64
 22  SCORE_IND_8         3930 non-null   int64
 23  RISQUE_IND_10       3930 non-null   object
 24  GAP_IND_10          3930 non-null   float64
 25  SCORE_IND_10        3930 non-null   int64
 26  RISQUE_IND_12       3930 non-null   object
 27  GAP_IND_12          3930 non-null   float64
 28  SCORE_IND_12        3930 non-null   int64
 29  RISQUE_IND_13       3930 non-null   object
 30  GAP_IND_13          3930 non-null   float64
 31  SCORE_IND_13        3930 non-null   int64
 32  RISQUE_IND_14       3930 non-null   object
 33  RISQUE_IND_3        3930 non-null   object
 34  RISQUE_IND_4        3930 non-null   object
 35  GAP_IND_4           3930 non-null   float64
 36  SCORE_IND_4         3930 non-null   int64
 37  RISQUE_IND_5        3930 non-null   object
 38  GAP_IND_5           3930 non-null   float64
 39  SCORE_IND_5         3930 non-null   int64
 40  RISQUE_IND_7_A      3930 non-null   object
 41  RISQUE_IND_7_B      3930 non-null   object
 42  RISQUE_IND_9        3930 non-null   object
 43  RISQUE_IND_6        3930 non-null   object
 44  GAP_IND_6           3930 non-null   float64
 45  SCORE_IND_6         3930 non-null   int64
 46  RISQUE_IND_20       3930 non-null   object
 47  GAP_IND_20          3930 non-null   float64
 48  SCORE_IND_20        3930 non-null   int64
 49  RISQUE_IND_21       3930 non-null   object
 50  RISQUE_IND_23       3930 non-null   object
 51  RISQUE_IND_24       3930 non-null   object
 52  GAP_IND_24          3930 non-null   float64
 53  SCORE_IND_24        3930 non-null   int64
 54  RISQUE_IND_25       3930 non-null   object
 55  GAP_IND_25          3930 non-null   float64
 56  SCORE_IND_25        3930 non-null   int64
 57  RISQUE_IND_26       3930 non-null   object
 58  GAP_IND_26          3930 non-null   float64
 59  SCORE_IND_26        3930 non-null   int64
 60  RISQUE_IND_27       3930 non-null   object
 61  RISQUE_IND_29       3930 non-null   object
 62  RISQUE_IND_32       3930 non-null   object
 63  RISQUE_IND_33       3930 non-null   object
 64  RISQUE_IND_34       3930 non-null   object
 65  RISQUE_IND_37       3930 non-null   object
 66  RATIO_IND_37        3930 non-null   float64
 67  RISQUE_IND_38       3930 non-null   object
 68  RISQUE_IND_39       3930 non-null   object
 69  RISQUE_IND_49       3930 non-null   object
 70  RISQUE_IND_57       3930 non-null   object
 71  RISQUE_IND_58       3930 non-null   object
dtypes: float64(16), int64(13), object(43)
memory usage: 2.2+ MB

In [39]:
filter_risk["CODE_REG_FISC"].value_counts()

CODE_REG_FISC
RN        3661
RSI        220
ND          46
CME_RD       2
CME          1
Name: count, dtype: int64

In [81]:
shiny = pd.read_csv("../data/BD_TVA_Shiny.csv", sep=",", encoding="latin-1",)

In [84]:
shiny["DATE_DERNIERE_VG"].isnull().sum()

np.int64(561)

In [51]:
M = (shiny["RISQUE_IND_15_A"]=="rouge") & (shiny["RISQUE_IND_15_B"]=="rouge")
shiny_risk = shiny[M]
shiny_risk

,NUM_IFU,NOM_MINEFID,ETAT,CODE_SECT_ACT,CODE_REG_FISC,STRUCTURES,ANNEE_FISCAL,DATE_DERNIERE_VG,DATE_DERNIERE_VP,DATE_DERNIERE_AVIS,...,RISQUE_IND_32,RISQUE_IND_33,RISQUE_IND_34,RATIO_IND_37,RISQUE_IND_37,RISQUE_IND_38,RISQUE_IND_39,RISQUE_IND_49,RISQUE_IND_57,RISQUE_IND_58
23,00042006N,INTERTEK BURKINA FASO LTD (INTERTEK BURKINA F...,ACTIF,7435.0,RN,DIRECTION GRANDES ENTREPRISES,2024.0,2021-06-17T00:00:00Z,2015-04-07T00:00:00Z,2021-11-18T00:00:00Z,...,vert,vert,vert,0.0,vert,vert,vert,Non disponible,Non disponible,Non disponible
24,00042006N,INTERTEK BURKINA FASO LTD (INTERTEK BURKINA F...,ACTIF,7435.0,RN,DIRECTION GRANDES ENTREPRISES,2025.0,2021-06-17T00:00:00Z,2015-04-07T00:00:00Z,2021-11-18T00:00:00Z,...,vert,vert,vert,0.0,vert,vert,vert,Non disponible,Non disponible,Non disponible
25,00042006N,INTERTEK BURKINA FASO LTD (INTERTEK BURKINA F...,ACTIF,7435.0,RN,DIRECTION GRANDES ENTREPRISES,2023.0,2021-06-17T00:00:00Z,2015-04-07T00:00:00Z,2021-11-18T00:00:00Z,...,vert,vert,vert,0.0,vert,vert,vert,Non disponible,Non disponible,Non disponible
26,00042006N,INTERTEK BURKINA FASO LTD (INTERTEK BURKINA F...,ACTIF,7435.0,RN,DIRECTION GRANDES ENTREPRISES,2020.0,2021-06-17T00:00:00Z,2015-04-07T00:00:00Z,2021-11-18T00:00:00Z,...,vert,vert,vert,0.0,vert,vert,vert,Non disponible,Non disponible,Non disponible
27,00042006N,INTERTEK BURKINA FASO LTD (INTERTEK BURKINA F...,ACTIF,7435.0,RN,DIRECTION GRANDES ENTREPRISES,2021.0,2021-06-17T00:00:00Z,2015-04-07T00:00:00Z,2021-11-18T00:00:00Z,...,vert,vert,vert,0.0,vert,vert,vert,Non disponible,Non disponible,Non disponible
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20876,RF2575186,KOURAOGO MATHIEU,ACTIF,514423.0,RN,NaN,NaN,NaN,NaN,NaN,...,vert,vert,vert,0.0,vert,vert,vert,Non disponible,Non disponible,Non disponible
20877,RF2580783,SAWADOGO NOAGA ADAMA,ACTIF,5246.0,RN,NaN,NaN,NaN,NaN,NaN,...,vert,vert,vert,0.0,vert,vert,vert,Non disponible,Non disponible,Non disponible
20880,RF2581303,CABINET CGEF AFRIQUE,ACTIF,7412.0,RN,NaN,NaN,NaN,NaN,NaN,...,vert,vert,vert,0.0,vert,vert,vert,Non disponible,Non disponible,Non disponible
20881,RF2581212,PHARMACIE DU BAM SARL,ACTIF,2421.0,RN,NaN,NaN,NaN,NaN,NaN,...,vert,vert,vert,0.0,vert,vert,vert,Non disponible,Non disponible,Non disponible
20883,RF2583618,MAIGA MAMADOU,ACTIF,5246.0,RN,NaN,NaN,NaN,NaN,NaN,...,vert,vert,vert,0.0,vert,vert,vert,Non disponible,Non disponible,Non disponible

In [50]:
shiny_risk.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14910 entries, 23 to 20883
Data columns (total 72 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   NUM_IFU             14906 non-null  object
 1   NOM_MINEFID         14738 non-null  object
 2   ETAT                14910 non-null  object
 3   CODE_SECT_ACT       13928 non-null  float64
 4   CODE_REG_FISC       14910 non-null  object
 5   STRUCTURES          13159 non-null  object
 6   ANNEE_FISCAL        12567 non-null  float64
 7   DATE_DERNIERE_VG    14349 non-null  object
 8   DATE_DERNIERE_VP    14349 non-null  object
 9   DATE_DERNIERE_AVIS  14349 non-null  object
 10  RISQUE_IND_15_A     14910 non-null  object
 11  RISQUE_IND_15_B     14910 non-null  object
 12  RISQUE_IND_1        14910 non-null  object
 13  GAP_IND_1           14910 non-null  float64
 14  SCORE_IND_1         14910 non-null  int64
 15  RISQUE_IND_2        14910 non-null  object
 16  GAP_IND_2           14910 non-null  float64
 17  SCORE_IND_2         14910 non-null  int64
 18  RISQUE_IND_3        14910 non-null  object
 19  RISQUE_IND_4        14910 non-null  object
 20  GAP_IND_4           14910 non-null  int64
 21  SCORE_IND_4         14910 non-null  int64
 22  RISQUE_IND_5        14910 non-null  object
 23  GAP_IND_5           14910 non-null  float64
 24  SCORE_IND_5         14910 non-null  int64
 25  RISQUE_IND_6        14910 non-null  object
 26  GAP_IND_6           14910 non-null  float64
 27  SCORE_IND_6         14910 non-null  int64
 28  RISQUE_IND_7_A      14910 non-null  object
 29  RISQUE_IND_7_B      14910 non-null  object
 30  RISQUE_IND_8        14910 non-null  object
 31  GAP_IND_8           14910 non-null  float64
 32  SCORE_IND_8         14910 non-null  int64
 33  RISQUE_IND_9        14910 non-null  object
 34  RISQUE_IND_10       14910 non-null  object
 35  GAP_IND_10          14910 non-null  float64
 36  SCORE_IND_10        14910 non-null  int64
 37  RISQUE_IND_12       14910 non-null  object
 38  GAP_IND_12          14910 non-null  float64
 39  SCORE_IND_12        14910 non-null  int64
 40  RISQUE_IND_13       14910 non-null  object
 41  GAP_IND_13          14910 non-null  float64
 42  SCORE_IND_13        14910 non-null  int64
 43  RISQUE_IND_14       14910 non-null  object
 44  RISQUE_IND_16       14910 non-null  object
 45  RISQUE_IND_20       14910 non-null  object
 46  GAP_IND_20          14910 non-null  float64
 47  SCORE_IND_20        14910 non-null  int64
 48  RISQUE_IND_21       14910 non-null  object
 49  RISQUE_IND_23       14910 non-null  object
 50  RISQUE_IND_24       14910 non-null  object
 51  GAP_IND_24          14910 non-null  float64
 52  SCORE_IND_24        14910 non-null  int64
 53  RISQUE_IND_25       14910 non-null  object
 54  GAP_IND_25          14910 non-null  float64
 55  SCORE_IND_25        14910 non-null  int64
 56  RISQUE_IND_26       14910 non-null  object
 57  GAP_IND_26          14910 non-null  float64
 58  SCORE_IND_26        14910 non-null  int64
 59  RISQUE_IND_27       14910 non-null  object
 60  RISQUE_IND_29       14910 non-null  object
 61  RISQUE_IND_30       14910 non-null  object
 62  RISQUE_IND_32       14910 non-null  object
 63  RISQUE_IND_33       14910 non-null  object
 64  RISQUE_IND_34       14910 non-null  object
 65  RATIO_IND_37        14910 non-null  float64
 66  RISQUE_IND_37       14910 non-null  object
 67  RISQUE_IND_38       14910 non-null  object
 68  RISQUE_IND_39       14910 non-null  object
 69  RISQUE_IND_49       14910 non-null  object
 70  RISQUE_IND_57       14910 non-null  object
 71  RISQUE_IND_58       14910 non-null  object
dtypes: float64(15), int64(14), object(43)
memory usage: 8.3+ MB

In [18]:
data_from_process.drop("DATE_IMMAT_y", axis=1, inplace=True)

In [13]:
import pandas as pd
pd.to_datetime(data_from_process["DATE_IMMAT_y"], errors="coerce")

0        NaT
1        NaT
2        NaT
3        NaT
4        NaT
          ..
795250   NaT
795251   NaT
795252   NaT
795253   NaT
795254   NaT
Name: DATE_IMMAT_y, Length: 795255, dtype: datetime64[ns]

In [ ]:
loader.dcf_activites.to_sql(
     name='dcf_activites',
    con=connect,
    schema='PROG_DCF',
    if_exists='append',  # Ajouter sans écraser
    index=False)

In [6]:
tva = loader._construct_bd_tva_complete(oracle_engine)

2025-10-16 09:03:40,972 - core.data_loader - INFO - Construction BD_TVA complète (reproduction R)
2025-10-16 09:03:46,872 - core.data_loader - INFO - BD_TVA construite (R-compatible): 20659 lignes en 5.89s

In [7]:
tva

,NUM_IFU,NOM,ANNEE_FISCAL,MONTANT_DECLARE,OP_TAXBLE_COURANTE_VENTES_PRESTATIONS_SERVICES_TRVX_IMMO_01,OP_TAXBLE_COURANTE_LIVRAISON_A_SOI_MEME_02,OP_TAXBLE_COURANTE_CESSION_IMMO_03,OP_TAXBLE_COURANTE_OPERATION_TAXABLE_TAUX_10PC_218,OP_TAXBLE_COURANTE_AUTRES_OPERATIONS_TAXABLES_04,OP_TAXBLE_MARCHE_CDE_VENTES_05,...,TVA_VENTE_SERVICES_IMPAYES_CREANCE_IRECOUVRABLE_20,TVA_VTE_SERVICE_RESILIES_21,AUTRES_DEDUCTIONS_22,CREDIT_TVA_NON_REMBOURSE_23,MONTANT_TVA_PAYABLE_AVIS_CREDIT_127,MONTANT_TVA_NET_A_PAYER_25,MONTANT_TOTAL_OPERATIONS_24,CREDIT_TVA_A_REMBOURSER_26,NB_DECLARATIONS,TVA_DECEMBRE
0,00000004U,SCIENCES CONSULTING & TRADE,2021,25419873,0,0,0,0,0,0,...,0,0,0,0,0,25419873,141221515,0,12,1433301
1,00000004U,SCIENCES CONSULTING & TRADE,2022,14163001,0,0,0,0,0,0,...,0,0,0,0,0,14163001,78683332,0,13,0
2,00000004U,SCIENCES CONSULTING & TRADE,2023,7079944,0,0,0,0,0,0,...,0,0,0,0,0,7079944,39333020,0,9,0
3,00000017X,LAURENT AZIZ TAPSOBA,2021,24447150,0,0,0,0,0,0,...,0,0,0,0,0,24447150,135817500,0,12,0
4,00000017X,LAURENT AZIZ TAPSOBA,2022,14788800,0,0,0,0,0,0,...,0,0,0,0,0,14788800,82160000,968922,12,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20654,00211828C,MAISON DE LA FEMME DE DEDOUGOU,2023,36000,0,0,0,0,0,0,...,0,0,0,0,0,36000,0,0,1,0
20655,00212172B,KGL TRANSPORT & HYDROCARBURE,2023,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
20656,00213088R,DE-KU-MWIN CLARISSE SOME,2023,169821,0,0,0,0,7519203,0,...,0,0,0,0,0,169821,497658833,179182,3,0
20657,00214258M,COMPAGNIE BURKINABE SAINT CHARLES,2023,383624,0,0,0,0,0,0,...,0,0,0,0,0,383624,0,0,1,383624
20658,00217633Y,PHARMACIE NADON NOUVELLE,2023,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,5601,1,0

In [29]:
tva["NUM_IFU"].value_counts()

NUM_IFU
00172087E    3
00000178X    3
00000176W    3
00000169N    3
00000157F    3
            ..
00200837E    1
00200905A    1
00201439J    1
00201497X    1
00201566X    1
Name: count, Length: 8654, dtype: int64

In [8]:
tva_deduc = loader._extract_dcf_tva_deduction(oracle_engine)
tva_deduc

2025-10-16 09:08:30,327 - core.data_loader - INFO - Extraction DCF_TVA_DEDUCTION
2025-10-16 09:08:38,592 - core.data_loader - INFO - DCF_TVA_DEDUCTION extraite: 100000 lignes en 8.26s

,NUM_IFU,NOM,ANNEE_FISCAL,MOIS_FISCAL,MONTANT_DECLARE,OP_TAXBLE_COURANTE_VENTES_PRESTATIONS_SERVICES_TRVX_IMMO_01,OP_TAXBLE_COURANTE_LIVRAISON_A_SOI_MEME_02,OP_TAXBLE_COURANTE_CESSION_IMMO_03,OP_NTAXBLE_EXPORTATIONS_09,OP_NTAXBLE_AUTRES_COMM_EXTERIEUR_VTE_SUSPENSION_TAXE_10,MONTANT_TVA_NET_A_PAYER_25,TVA_DEDUCTIBLE_PÉRIODE_16
0,00000004U,SCIENCES CONSULTING & TRADE,2021,1,2231195,0,0,0,0,0,2231195,0
1,00000017X,LAURENT AZIZ TAPSOBA,2021,1,0,0,0,0,0,0,0,0
2,00000019F,SYNOVIE SARL,2021,1,288882,1617034,0,0,0,0,288882,2184
3,00000051J,VERDOYANT,2021,1,4336360,31396738,0,0,0,0,4336360,1315053
4,00000063X,HAGE MATERIAUX,2021,1,71802019,761200450,0,0,9670000,0,71802019,21855823
...,...,...,...,...,...,...,...,...,...,...,...,...
99995,00158378A,AXIAL,2023,12,6563197,0,0,0,0,0,6563197,0
99996,00158378A,AXIAL,2023,12,1464750,0,0,0,0,0,1464750,0
99997,00166442L,NOUR BATIMENT ET TRAVAUX PUBLICS,2023,12,0,0,0,0,0,0,0,0
99998,00184094H,SOCIETE MATURINZI,2023,12,1372410,7624500,0,0,0,0,1372410,0
99999,00198615G,SERVICES AGRO-PASTORAUX DE L'ESPERANCE,2023,12,0,0,0,0,0,0,0,0

In [4]:
dgd = loader._extract_dgd_complete_with_nomenclature(oracle_engine)
dgd

2025-10-17 12:19:49,681 - core.data_loader - INFO - Extraction DGD complète avec nomenclature
2025-10-17 12:21:25,166 - core.data_loader - INFO - DGD extraite de la base Oracle: 720187 lignes

DGD extraite de la base Oracle: 720187 lignes

2025-10-17 12:21:27,609 - core.data_loader - INFO - Nomenclature fusionnée sur Code_Chapitre
2025-10-17 12:21:27,612 - core.data_loader - INFO - DGD complète extraite: 720187 lignes en 97.93s

,CODE_BUREAU,LIB_BUREAU,NUM_LIQUIDATION,DATE_LIQUIDATION,NUM_ARTICLE,NOMENCLATURE8,NOMENCLATURE10,LIBELLE,PAYS_ORIGINE,PAYS_DESTINATION1,...,TEP,TPC,TVT,ANNEE,CODE_CHAPITRE,Code Titre,Libellé_Titre,Lib_titre,Code_Chapitre,Lib_Chapitre
0,BFC02,OUAGA AEROPORT,L14158,2022-12-28,1,90189000,9018900000,"INSTRU &APP PR LA MEDECINE,CHIRURGIE,L'ART DEN...",Chine,Chine,...,NaN,NaN,NaN,2022,90,XVIII,"Instruments et appareils d'optique, de photogr...","Instruments et appareils d'optique, de photogr...",90,"INSTRUMENTS ET APPAREILS D'OPTIQUE, DE PHOTOGR..."
1,BFC03,OUAGA CDP,L5125,2023-07-17,2,90321000,9032100000,THERMOSTATS,Luxembourg,Luxembourg,...,NaN,NaN,NaN,2023,90,XVIII,"Instruments et appareils d'optique, de photogr...","Instruments et appareils d'optique, de photogr...",90,"INSTRUMENTS ET APPAREILS D'OPTIQUE, DE PHOTOGR..."
2,BFC03,OUAGA CDP,L5125,2023-07-17,1,83021000,8302100000,CHARNIERES DE TOUS GENRES (Y COMPRIS LES PAUME...,Luxembourg,Luxembourg,...,NaN,NaN,NaN,2023,83,XV,Métaux communs et ouvrages en ces métaux. Chap...,Métaux communs et ouvrages en ces métaux. Chap...,83,OUVRAGES DIVERS EN METAUX COMMUNS
3,BFC03,OUAGA CDP,L8494,2023-11-15,4,84189900,8418990000,PARTIES AUTRE QUE MEUBLES CONCUS POUR RECEVOIR...,Luxembourg,Luxembourg,...,NaN,NaN,NaN,2023,84,XVI,Machines et appareils matériel électrique et l...,Machines et appareils matériel électrique et l...,84,"REACTEURS NUCLEAIRES, CHAUDIERES, MACHINES, AP..."
4,BFC03,OUAGA CDP,L8494,2023-11-15,2,84145900,8414590000,VENTILATEURS AUTRES QUE CEUX DU 8414.51,Luxembourg,Luxembourg,...,NaN,NaN,NaN,2023,84,XVI,Machines et appareils matériel électrique et l...,Machines et appareils matériel électrique et l...,84,"REACTEURS NUCLEAIRES, CHAUDIERES, MACHINES, AP..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
720182,BFW01,BOBO GARE,L14765,2025-09-17,1,87032320,8703232090,"VEHICULE USAGE,A MOTEUR A PISTON ALLUM PAR ETI...",Japon,Togo,...,NaN,NaN,NaN,2025,87,XVII,"Matériel de transport (Avion, bateau,voitures ...","Matériel de transport (Avion, bateau,voitures ...",87,"VOITURES AUTOMOBILES, TRACTEURS, CYCLES ET AUT..."
720183,BFC15,BVA (BUREAU VEHICULES AUTOMOBILES),L29415,2025-09-25,1,87032320,8703232010,"VEHICULE USAGE,A MOTEUR A PISTON ALLUM PAR ETI...",Japon,Etats-Unis,...,NaN,NaN,NaN,2025,87,XVII,"Matériel de transport (Avion, bateau,voitures ...","Matériel de transport (Avion, bateau,voitures ...",87,"VOITURES AUTOMOBILES, TRACTEURS, CYCLES ET AUT..."
720184,BFC15,BVA (BUREAU VEHICULES AUTOMOBILES),L30655,2025-10-07,1,87032320,8703232090,"VEHICULE USAGE,A MOTEUR A PISTON ALLUM PAR ETI...",Japon,Japon,...,NaN,NaN,NaN,2025,87,XVII,"Matériel de transport (Avion, bateau,voitures ...","Matériel de transport (Avion, bateau,voitures ...",87,"VOITURES AUTOMOBILES, TRACTEURS, CYCLES ET AUT..."
720185,BFC15,BVA (BUREAU VEHICULES AUTOMOBILES),L31461,2025-10-14,1,87032320,8703232090,"VEHICULE USAGE,A MOTEUR A PISTON ALLUM PAR ETI...",Etats-Unis,Etats-Unis,...,NaN,NaN,NaN,2025,87,XVII,"Matériel de transport (Avion, bateau,voitures ...","Matériel de transport (Avion, bateau,voitures ...",87,"VOITURES AUTOMOBILES, TRACTEURS, CYCLES ET AUT..."
720186,BFW01,BOBO GARE,L16297,2025-10-14,1,87032320,8703232010,"VEHICULE USAGE,A MOTEUR A PISTON ALLUM PAR ETI...",Japon,Etats-Unis,...,NaN,NaN,NaN,2025,87,XVII,"Matériel de transport (Avion, bateau,voitures ...","Matériel de transport (Avion, bateau,voitures ...",87,"VOITURES AUTOMOBILES, TRACTEURS, CYCLES ET AUT..."

In [5]:
dgd["ANNEE"].value_counts()

ANNEE
2024    239875
2025    221923
2023    211055
2022     47334
Name: count, dtype: int64

In [11]:
programm = loader._extract_programmation_controles(oracle_engine)
programm

2025-10-16 09:55:57,473 - core.data_loader - INFO - Extraction programmation et contrôles
2025-10-16 09:56:40,623 - core.data_loader - INFO - Programmation extraite: 652474 lignes en 43.15s

,NUM_IFU,DATE_IMMAT,NOM_MINEFID,DATE_DERNIERE_VG,DATE_DERNIERE_VP,DATE_DERNIERE_AVIS,DERNIERE_GESTION_SOUMIS_VERIF
0,00026275V,2010-04-21 00:00:00,MAMADOU TIEMTORE (COMPTOIR BURKINABE DE MARCHA...,None,NaT,None,None
1,00026276G,2010-04-21 00:00:00,ISSA TRAORE (I. T. F. SERVICES),None,NaT,None,None
2,00026277S,2010-04-21 00:00:00,ABDOUL MOUMOUNI PITROÏPA (TRICOM),2022-03-24 00:00:00,NaT,None,None
3,00026279M,2010-04-21 00:00:00,ALPHONSINE KANSOLE (KA MODE),None,NaT,None,None
4,00026281W,2010-04-21 00:00:00,DELWENDE SAMUEL BANDE (VISINE CONSEIL),None,NaT,None,None
...,...,...,...,...,...,...,...
652469,00284006H,2025-09-15 14:05:59,HADARA BELEM (BELHADA SERVICES FASHION),None,NaT,None,None
652470,00284007T,2025-09-15 14:07:14,RASMANE COMPAORE (RAHAB SOLUTION BF),None,NaT,None,None
652471,00283999K,2025-09-15 13:56:10,SALIF BAYO (ELEVAGE),None,NaT,None,None
652472,00284008U,2025-09-15 14:08:35,KADIDIATOU SANKARA (ETS SANKARA KADIDIATOU SER...,None,NaT,None,None
652473,00284009J,2025-09-15 14:09:55,ABBAS KOANDA (KOANDA ABBAS IMPORT- EXPORT),None,NaT,None,None

In [15]:
programm["NUM_IFU"].value_counts()

NUM_IFU
00033840Y    2
00071340X    2
00076174C    2
00005550Y    2
00000181B    2
            ..
00116807M    1
00116822J    1
00116844U    1
00116816Z    1
00116814B    1
Name: count, Length: 652185, dtype: int64

In [13]:
benefices = loader._extract_benefices_complete(oracle_engine)
benefices

2025-10-16 10:22:38,495 - core.data_loader - INFO - Extraction bénéfices complets
2025-10-16 10:30:01,013 - core.data_loader - INFO - Bénéfices extraits: 863075 lignes en 442.52s

          NUM_IFU  ANNEE_FISCAL CODE_ELT_LIQ  VALEUR_NUMERIQUE TYPE_BENEFICE
0       RF2126204          2022          118               NaN         IBICA
1       RF2126204          2022          120               NaN         IBICA
2       RF2126204          2022           69               NaN         IBICA
3       RF2126204          2022          117               NaN         IBICA
4       RF2126204          2022          115               NaN         IBICA
...           ...           ...          ...               ...           ...
863070  00276594F          2024          122               NaN          IBNC
863071  00276594F          2024          228               NaN          IBNC
863072  00276594F          2024          115               NaN          IBNC
863073  00276594F          2024          119               NaN          IBNC
863074  00276594F          2024           69               NaN          IBNC

[863075 rows x 5 columns]

In [4]:
insd = loader._extract_insd(oracle_engine)
insd

2025-10-17 10:27:30,367 - core.data_loader - INFO - Extraction INSD
2025-10-17 10:27:55,108 - core.data_loader - INFO - INSD extraite: 8818 lignes en 24.74s

,NUMERO_IFU,ID_INSD,ANNEE,FDP_ACQAPCREAT,BLLDS_ACQAPCREAT,BLLDS_VIREPOSTPOST,XA_MARGCOMMERC,XB_CA,XE_RESULT_EXPL,ETATTVA_ANNEEN,...,TOTAL_PVENDUEPAYS,AZ_TACTIFIMMOB_BRUT,BI_CLIENTS_NET,DN_PRCCT_NET,CP_TCPREA_NET,TPRC_ANNEEN,FR_ANNEEN,RK_CHARGDEPERSONNEL,RL_DOTAMORTPROVIDEP,XH_RESULTAT_HAO
0,00005679C,OUA2000A865-2023,2023,0,0,0,0,78988250,5249068,0.0,...,0.0,0.0,34944000.0,0.0,41411367.0,0.0,41411367.0,-1113600,0,0
128,00002168P,OUA2003 B 1036-2023,2023,0,0,0,-217496758,218836090,-190037212,25045963.0,...,0.0,2100000.0,0.0,0.0,53643287.0,0.0,53643287.0,-1531200,-600000,0
129,00009542B,OUA2007 A 043-2023,2023,0,0,0,-7590000,86629833,11985833,0.0,...,0.0,5321000.0,47596045.0,0.0,3902833.0,0.0,-1418167.0,-14820000,-1612000,0
130,00076515X,OUA2016B4143-2023,2023,0,0,0,0,139148530,10339625,0.0,...,0.0,67836302.0,24063000.0,0.0,-20715288.0,0.0,-37514124.0,-36437984,-7877052,-3776429
131,00099067P,OUA2017A9447-2023,2023,0,0,0,72750802,2492253700,9621020,73447.0,...,0.0,17101163.0,0.0,0.0,30959561.0,0.0,13858398.0,-15567200,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
359102,00017238S,ZNR2013M002,2022,0,0,0,0,298468703,43534840,2556640.0,...,0.0,284480000.0,132506290.0,0.0,294863718.0,0.0,274918527.0,-7262650,-9632112,0
359203,00106447T,OUA2022M0246,2022,0,0,0,0,80157780,-25268703,0.0,...,0.0,202399999.0,15175897.0,0.0,49498905.0,0.0,-105542785.0,-17871901,-28361811,0
359204,00023338R,OUA2021M4689,2022,0,0,0,0,516227699,81390466,159702807.0,...,0.0,112987752.0,303589301.0,0.0,-155026787.0,26115693.0,-167238466.0,130845195,38386133,0
359205,00007211D,OUA2016M5335,2022,0,0,0,0,69199789,1904373,0.0,...,0.0,308754499.0,3227527.0,0.0,-142661269.0,0.0,-291898392.0,40441530,12566572,0
359206,00075456R,OUA2016B3421,2022,0,0,0,12439511,121529750,6514376,3656160.0,...,0.0,6968200.0,125185910.0,0.0,9593183.0,0.0,7680830.0,2530173,1565565,0

In [11]:
insd.duplicated().value_counts()

True     1527753
False       8818
Name: count, dtype: int64

In [10]:
insd[["NUMERO_IFU","ANNEE"]].duplicated().value_counts()

True     1529159
False       7412
Name: count, dtype: int64

In [12]:
insd.drop_duplicates()

,NUMERO_IFU,ID_INSD,ANNEE,FDP_ACQAPCREAT,BLLDS_ACQAPCREAT,BLLDS_VIREPOSTPOST,XA_MARGCOMMERC,XB_CA,XE_RESULT_EXPL,ETATTVA_ANNEEN,...,TOTAL_PVENDUEPAYS,AZ_TACTIFIMMOB_BRUT,BI_CLIENTS_NET,DN_PRCCT_NET,CP_TCPREA_NET,TPRC_ANNEEN,FR_ANNEEN,RK_CHARGDEPERSONNEL,RL_DOTAMORTPROVIDEP,XH_RESULTAT_HAO
0,00005679C,OUA2000A865-2023,2023,0,0,0,0,78988250,5249068,0.0,...,0.0,0.0,34944000.0,0.0,41411367.0,0.0,41411367.0,-1113600,0,0
128,00002168P,OUA2003 B 1036-2023,2023,0,0,0,-217496758,218836090,-190037212,25045963.0,...,0.0,2100000.0,0.0,0.0,53643287.0,0.0,53643287.0,-1531200,-600000,0
129,00009542B,OUA2007 A 043-2023,2023,0,0,0,-7590000,86629833,11985833,0.0,...,0.0,5321000.0,47596045.0,0.0,3902833.0,0.0,-1418167.0,-14820000,-1612000,0
130,00076515X,OUA2016B4143-2023,2023,0,0,0,0,139148530,10339625,0.0,...,0.0,67836302.0,24063000.0,0.0,-20715288.0,0.0,-37514124.0,-36437984,-7877052,-3776429
131,00099067P,OUA2017A9447-2023,2023,0,0,0,72750802,2492253700,9621020,73447.0,...,0.0,17101163.0,0.0,0.0,30959561.0,0.0,13858398.0,-15567200,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1536466,00017238S,ZNR2013M002,2022,0,0,0,0,298468703,43534840,2556640.0,...,0.0,284480000.0,132506290.0,0.0,294863718.0,0.0,274918527.0,-7262650,-9632112,0
1536567,00106447T,OUA2022M0246,2022,0,0,0,0,80157780,-25268703,0.0,...,0.0,202399999.0,15175897.0,0.0,49498905.0,0.0,-105542785.0,-17871901,-28361811,0
1536568,00023338R,OUA2021M4689,2022,0,0,0,0,516227699,81390466,159702807.0,...,0.0,112987752.0,303589301.0,0.0,-155026787.0,26115693.0,-167238466.0,130845195,38386133,0
1536569,00007211D,OUA2016M5335,2022,0,0,0,0,69199789,1904373,0.0,...,0.0,308754499.0,3227527.0,0.0,-142661269.0,0.0,-291898392.0,40441530,12566572,0
1536570,00075456R,OUA2016B3421,2022,0,0,0,12439511,121529750,6514376,3656160.0,...,0.0,6968200.0,125185910.0,0.0,9593183.0,0.0,7680830.0,2530173,1565565,0

In [4]:
contribuable_data = loader.run_full_analysis()

2025-10-15 10:30:53,831 - core.data_loader - INFO - === DÉBUT DE L'ANALYSE COMPLÈTE ===
2025-10-15 10:30:53,834 - core.data_loader - INFO - === EXTRACTION COMPLÈTE ORACLE (Reproduction Scripts R) ===
2025-10-15 10:30:54,008 - core.data_loader - INFO - Extraction contribuables
2025-10-15 10:31:26,708 - core.data_loader - INFO - Contribuables extraits: 215882/215882 après exclusions en 32.70s
2025-10-15 10:31:26,710 - core.data_loader - INFO - Construction BD_TVA complète (reproduction R)
2025-10-15 10:31:35,127 - core.data_loader - INFO - BD_TVA construite (R-compatible): 20659 lignes en 8.42s
2025-10-15 10:31:35,128 - core.data_loader - INFO - Extraction DCF_TVA_DEDUCTION
2025-10-15 10:31:41,937 - core.data_loader - INFO - DCF_TVA_DEDUCTION extraite: 100000 lignes en 6.81s
2025-10-15 10:31:41,939 - core.data_loader - INFO - Extraction DGD complète avec nomenclature
2025-10-15 10:36:36,854 - core.data_loader - ERROR - Erreur lors de l'extraction DGD: 'DataLoader' object has no attribute 'nomenclature_sh'
2025-10-15 10:36:37,500 - core.data_loader - INFO - Extraction programmation et contrôles
2025-10-15 10:37:22,168 - core.data_loader - INFO - Programmation extraite: 652474 lignes en 44.67s
2025-10-15 10:37:22,169 - core.data_loader - INFO - Extraction bénéfices complets
2025-10-15 10:43:15,219 - core.data_loader - INFO - Bénéfices extraits: 863075 lignes en 353.05s
2025-10-15 10:43:15,244 - core.data_loader - INFO - === FUSION DES DONNÉES ===
2025-10-15 10:43:20,890 - core.data_loader - INFO - Données fusionnées: 1419453 lignes, 65 colonnes

In [12]:
contribuable_data

NameError: name 'contribuable_data' is not defined

In [12]:
contribuable_data["ANNEE_FISCAL_x"].value_counts()

ANNEE_FISCAL_x
2023.0    301263
2022.0    290830
2021.0    265623
Name: count, dtype: int64

In [11]:
contribuable_data["ANNEE_FISCAL_y"].value_counts()

ANNEE_FISCAL_y
2024.0    235707
2023.0    232415
2022.0    220476
2021.0    196924
2020.0    174435
2019.0    157990
2025.0      3388
Name: count, dtype: int64

In [7]:
contribuable_data["NUM_IFU"].value_counts()

NUM_IFU
00144015D    1440
00157569F    1188
00030439G    1182
00144016M     945
00116857X     864
             ...
00117776R       1
00007565C       1
00007564B       1
00007563F       1
00117760A       1
Name: count, Length: 215882, dtype: int64

In [7]:
merged_data = loader.run_extract_merge()

2025-12-17 11:26:19,551 - core.data_loader - INFO - === EXTRACTION & FUSION ===
2025-12-17 11:26:19,552 - core.data_loader - INFO -  1.=== EXTRACTION COMPLÈTE ORACLE (Reproduction Scripts R) ===
2025-12-17 11:26:19,770 - core.data_loader - INFO - Extraction contribuables
2025-12-17 11:30:45,222 - core.data_loader - INFO - Exclusions appliquées: 4249 IFU exclus (6204 dans la liste d'exclusion)
2025-12-17 11:30:45,224 - core.data_loader - INFO - Contribuables extraits: 669966/674215 après exclusions en 265.45s
2025-12-17 11:30:45,224 - core.data_loader - INFO - Construction BD_TVA complète (reproduction R)
2025-12-17 11:31:06,907 - core.data_loader - INFO - BD_TVA construite (R-compatible): 59034 lignes en 21.68s
2025-12-17 11:31:06,908 - core.data_loader - INFO - Extraction DCF_TVA_DEDUCTION
2025-12-17 11:31:48,421 - core.data_loader - INFO - DCF_TVA_DEDUCTION extraite: 62082 lignes en 41.51s
2025-12-17 11:31:48,421 - core.data_loader - INFO - Extraction DGD complète avec nomenclature
2025-12-17 11:32:22,547 - core.data_loader - INFO - DGD extraite de la base Oracle: 35143 lignes
2025-12-17 11:32:22,548 - core.data_loader - INFO - DGD complète extraite: 35143 lignes en 34.13s
2025-12-17 11:32:22,548 - core.data_loader - INFO - Extraction programmation et contrôles
2025-12-17 11:36:02,686 - core.data_loader - INFO - Programmation extraite: 674497 lignes en 220.14s
2025-12-17 11:36:02,686 - core.data_loader - INFO - Extraction bénéfices complets
2025-12-17 11:44:07,328 - core.data_loader - INFO - Bénéfices extraits: 830802 lignes en 484.64s
2025-12-17 11:44:07,328 - core.data_loader - INFO - Extraction INSD
2025-12-17 11:44:54,750 - core.data_loader - INFO - INSD extraite: 8818 lignes en 47.42s
2025-12-17 11:44:54,781 - core.data_loader - INFO - 2.=== FUSION DES DONNÉES ===
2025-12-17 11:44:55,006 - core.data_loader - INFO - Fusion BD_TVA + TVA_DEDUCTIONS réalisée: (86151, 50)
2025-12-17 11:44:55,282 - core.data_loader - INFO - Fusion TVA + DGD réalisée: (104683, 58)
2025-12-17 11:44:58,319 - core.data_loader - INFO - Fusion avec CONTRIBUABLES réalisée: (755066, 79)
2025-12-17 11:45:00,409 - core.data_loader - INFO - Fusion avec INSD réalisée: (757078, 99)
2025-12-17 11:45:02,708 - core.data_loader - INFO - Fusion avec PROGRAMMATION réalisée: (757952, 103)
2025-12-17 11:45:04,857 - core.data_loader - INFO - Fusion avec BENEFICES réalisée: (1091100, 107)
2025-12-17 11:45:04,857 - core.data_loader - INFO - Données fusionnées finales: 1091100 lignes, 107 colonnes

In [9]:
from core.risk_compute import RiskComputer

In [10]:
computer = RiskComputer()