In [ ]:
import pandas as pd
from indicateurs import TVAIndicators,ControleIndicators
from core.eligible_builder import EligibleBuilder
from core.risk_compute import RiskComputer

In [2]:
  BASE_COLUMNS = [
            "NUM_IFU",
            "NOM_MINEFID",        # Raison sociale
            "ETAT",               # État du contribuable
            "CODE_SECT_ACT",      # Code secteur d'activité
            "CODE_REG_FISC",      # Régime fiscal (CME, RSI, RNI, etc.)
            "STRUCTURES",         # Structure de rattachement
            "ANNEE_FISCAL",       # Année fiscale
            "DATE_DERNIERE_VG",   # Date dernière vérification générale
            "DATE_DERNIERE_VP",   # Date dernière vérification ponctuelle
            "DATE_DERNIERE_AVIS", # Date dernier avis de vérification
        ]

In [ ]:
merged_df = pd.read_csv("D:/DGI/project/anarisk-r/DCF_PROG_02_02_2026.csv",encoding='latin1' )
print(f"Nombre de lignes chargées: {len(merged_df)}")
print(f"Nombre de colonnes: {len(merged_df.columns)}")

Nombre de lignes chargées: 661138
Nombre de colonnes: 170

In [4]:
merged_df.drop_duplicates(inplace=True)
print(f"Nombre de lignes après suppression des doublons: {len(merged_df)}")

Nombre de lignes après suppression des doublons: 661000

In [ ]:
risk_computer = RiskComputer()

2026-02-05 11:43:53,198 [core.risk_compute] Chargement des données de référence...
2026-02-05 11:43:53,767 [core.risk_compute] NON_EIGIBLE.xlsx chargé: 6984 IFU a exclur
2026-02-05 11:43:53,781 [core.risk_compute] Entreprises_LIEES.xlsx chargé: 100 lignes

In [6]:
merged_data_eligible = risk_computer.exclude_non_eligible(merged_df)

2026-02-05 11:44:05,923 [core.risk_compute] Exclusion non-éligibles: 30705 contribuables exclus sur 661000

In [7]:
split_df = risk_computer.data_spliter_regime(merged_data_eligible)

2026-02-05 11:44:25,046 [core.risk_compute] DCF_PROG après suppression doublons: 630295 lignes (était 630295)
2026-02-05 11:44:25,103 [core.risk_compute] DCF_PROG_RNI: 21263 contribuables
2026-02-05 11:44:25,148 [core.risk_compute] DCF_PROG_RSI: 19338 contribuables
2026-02-05 11:44:25,429 [core.risk_compute] DCF_PROG_ND: 327417 contribuables
2026-02-05 11:44:25,627 [core.risk_compute] DCF_PROG_CME: 179254 contribuables
2026-02-05 11:44:25,633 [core.risk_compute] DCF_PROG_CSB: 187 contribuables
2026-02-05 11:44:25,633 [core.risk_compute] Données séparées en 5 régimes fiscaux

In [8]:
merged_data_nd = risk_computer.exclude_non_eligible(split_df["DCF_PROG_ND"])

2026-02-05 11:45:38,666 [core.risk_compute] Exclusion non-éligibles: 0 contribuables exclus sur 327417

In [ ]:
resultat_rni = risk_computer.calculate_all_indicators(merged_data_nd)

2026-02-05 11:46:39,249 [core.risk_compute] === CALCUL DE 32 INDICATEURS ===
2026-02-05 11:46:39,487 [core.risk_compute] Colonnes de base initialisées: 11 colonnes

In [ ]:
resultat_rni

,NUM_IFU,NOM_MINEFID,ETAT,CODE_SECT_ACT,CODE_REG_FISC,STRUCTURES,ANNEE_FISCAL,DATE_DERNIERE_VG,DATE_DERNIERE_VP,DATE_DERNIERE_AVIS,...,RISQUE_IND_32,RISQUE_IND_33,RISQUE_IND_34,RISQUE_IND_37,RATIO_IND_37,RISQUE_IND_38,RISQUE_IND_39,RISQUE_IND_49,RISQUE_IND_57,RISQUE_IND_58
0,00026269T,FOLIDIA DIT JOEL TANKOANO (LYCEE PRIVE EMMAUS),ACTIF,8021.0,RN,DME/HAUTS-BASSINS,NaN,2017-04-13T00:00:00Z,2023-01-25T00:00:00Z,2023-10-11T00:00:00Z,...,vert,vert,vert,vert,0.0,vert,vert,Non disponible,Non disponible,Non disponible
1,00026786L,LES ELITES BATISSEURS DU FASO (LES ELITES BAT...,ACTIF,4521.0,RN,DME/CENTRE II,2025.0,2023-08-18T00:00:00Z,2020-06-02T00:00:00Z,2024-01-26T00:00:00Z,...,vert,vert,vert,vert,0.0,vert,vert,Non disponible,Non disponible,Non disponible
2,00026786L,LES ELITES BATISSEURS DU FASO (LES ELITES BAT...,ACTIF,4521.0,RN,DME/CENTRE II,2017.0,2023-08-18T00:00:00Z,2020-06-02T00:00:00Z,2024-01-26T00:00:00Z,...,vert,vert,vert,vert,0.0,vert,vert,Non disponible,Non disponible,Non disponible
3,00026786L,LES ELITES BATISSEURS DU FASO (LES ELITES BAT...,ACTIF,4521.0,RN,DME/CENTRE II,2018.0,2023-08-18T00:00:00Z,2020-06-02T00:00:00Z,2024-01-26T00:00:00Z,...,vert,vert,vert,vert,0.0,vert,vert,Non disponible,Non disponible,Non disponible
4,00026786L,LES ELITES BATISSEURS DU FASO (LES ELITES BAT...,ACTIF,4521.0,RN,DME/CENTRE II,2019.0,2023-08-18T00:00:00Z,2020-06-02T00:00:00Z,2024-01-26T00:00:00Z,...,vert,vert,vert,vert,0.0,vert,vert,Non disponible,Non disponible,Non disponible
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21258,RF2581303,CABINET CGEF AFRIQUE,ACTIF,7412.0,RN,NaN,NaN,NaN,NaN,NaN,...,vert,vert,vert,vert,0.0,vert,vert,Non disponible,Non disponible,Non disponible
21259,RF2581212,PHARMACIE DU BAM SARL,ACTIF,2421.0,RN,NaN,NaN,NaN,NaN,NaN,...,vert,vert,vert,vert,0.0,vert,vert,Non disponible,Non disponible,Non disponible
21260,00293588R,STE COOPERATIVE AVEC CONSEIL D'ADMINISTRATION ...,ACTIF,5510.0,RN,NaN,NaN,2025-12-09T14:54:29Z,2025-12-09T14:54:29Z,2025-12-09T14:54:29Z,...,vert,vert,vert,vert,0.0,vert,vert,Non disponible,Non disponible,Non disponible
21261,RF2583618,MAIGA MAMADOU,ACTIF,5246.0,RN,NaN,NaN,NaN,NaN,NaN,...,vert,vert,vert,vert,0.0,vert,vert,Non disponible,Non disponible,Non disponible
21262,00295773R,KADRU REGIE & COM (KADRU REGIE & COM),ACTIF,7435.0,RN,NaN,NaN,2025-12-26T17:39:31Z,2025-12-26T17:39:31Z,2025-12-26T17:39:31Z,...,vert,vert,vert,vert,0.0,vert,vert,Non disponible,Non disponible,Non disponible

In [8]:
R = risk_computer.run(local_mode=True)

2026-01-14 09:44:13,880 [core.risk_compute] === DÉMARRAGE PRCOCESSE: RECUPERATION & CALCULE DES RISK ===
2026-01-14 09:44:13,880 [core.risk_compute] Données chargées et mergées avec succès.
2026-01-14 09:44:13,880 [core.risk_compute] === CALCUL DE 32 INDICATEURS ===
2026-01-14 09:44:13,898 [core.risk_compute] Colonnes de base initialisées: 11 colonnes
2026-01-14 09:46:36,739 [core.risk_compute] Calcul de tous les indicateurs terminé
2026-01-14 09:46:37,325 [core.risk_compute] === ANALYSE TERMINÉE EN 142.87s ===

In [10]:
R["status"]

'success'

In [8]:
bd_tva_shiny =pd.read_csv("../data/bd_tva_shiny.csv", delimiter=",", encoding="latin1",  on_bad_lines='skip')

In [9]:
bd_tva_shiny

,NUM_IFU,NOM_MINEFID,ETAT,CODE_SECT_ACT,CODE_REG_FISC,STRUCTURES,ANNEE_FISCAL,DATE_DERNIERE_VG,DATE_DERNIERE_VP,DATE_DERNIERE_AVIS,...,RISQUE_IND_32,RISQUE_IND_33,RISQUE_IND_34,RATIO_IND_37,RISQUE_IND_37,RISQUE_IND_38,RISQUE_IND_39,RISQUE_IND_49,RISQUE_IND_57,RISQUE_IND_58
0,00026269T,FOLIDIA DIT JOEL TANKOANO (LYCEE PRIVE EMMAUS),ACTIF,8021.0,RN,DME/HAUTS-BASSINS,NaN,2017-04-13T00:00:00Z,2023-01-25T00:00:00Z,2023-10-11T00:00:00Z,...,vert,vert,vert,0.0,vert,vert,vert,Non disponible,Non disponible,Non disponible
1,00026786L,LES ELITES BATISSEURS DU FASO (LES ELITES BAT...,ACTIF,4521.0,RN,DME/CENTRE II,2025.0,2023-08-18T00:00:00Z,2020-06-02T00:00:00Z,2024-01-26T00:00:00Z,...,vert,vert,vert,0.0,vert,vert,vert,Non disponible,Non disponible,Non disponible
2,00026786L,LES ELITES BATISSEURS DU FASO (LES ELITES BAT...,ACTIF,4521.0,RN,DME/CENTRE II,2017.0,2023-08-18T00:00:00Z,2020-06-02T00:00:00Z,2024-01-26T00:00:00Z,...,vert,vert,vert,0.0,vert,vert,vert,Non disponible,Non disponible,Non disponible
3,00026786L,LES ELITES BATISSEURS DU FASO (LES ELITES BAT...,ACTIF,4521.0,RN,DME/CENTRE II,2018.0,2023-08-18T00:00:00Z,2020-06-02T00:00:00Z,2024-01-26T00:00:00Z,...,vert,vert,vert,0.0,vert,vert,vert,Non disponible,Non disponible,Non disponible
4,00026786L,LES ELITES BATISSEURS DU FASO (LES ELITES BAT...,ACTIF,4521.0,RN,DME/CENTRE II,2019.0,2023-08-18T00:00:00Z,2020-06-02T00:00:00Z,2024-01-26T00:00:00Z,...,vert,vert,vert,0.0,vert,vert,vert,Non disponible,Non disponible,Non disponible
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20880,RF2581303,CABINET CGEF AFRIQUE,ACTIF,7412.0,RN,NaN,NaN,NaN,NaN,NaN,...,vert,vert,vert,0.0,vert,vert,vert,Non disponible,Non disponible,Non disponible
20881,RF2581212,PHARMACIE DU BAM SARL,ACTIF,2421.0,RN,NaN,NaN,NaN,NaN,NaN,...,vert,vert,vert,0.0,vert,vert,vert,Non disponible,Non disponible,Non disponible
20882,00293588R,STE COOPERATIVE AVEC CONSEIL D'ADMINISTRATION ...,ACTIF,5510.0,RN,NaN,NaN,2025-12-09T14:54:29Z,2025-12-09T14:54:29Z,2025-12-09T14:54:29Z,...,vert,vert,vert,0.0,vert,vert,vert,Non disponible,Non disponible,Non disponible
20883,RF2583618,MAIGA MAMADOU,ACTIF,5246.0,RN,NaN,NaN,NaN,NaN,NaN,...,vert,vert,vert,0.0,vert,vert,vert,Non disponible,Non disponible,Non disponible
20884,00295773R,KADRU REGIE & COM (KADRU REGIE & COM),ACTIF,7435.0,RN,NaN,NaN,2025-12-26T17:39:31Z,2025-12-26T17:39:31Z,2025-12-26T17:39:31Z,...,vert,vert,vert,0.0,vert,vert,vert,Non disponible,Non disponible,Non disponible

In [14]:
# Version probablement voulue :
diff = bd_tva_shiny[~bd_tva_shiny.isin(resultat_rni.drop(columns="ANNEE"))].dropna(how='all')

# Ou plus clairement :
#diff = bd_tva_shiny[~bd_tva_shiny.index.isin(resultat_rni.index)]

In [20]:
bd_tva_shiny[:1]

,NUM_IFU,NOM_MINEFID,ETAT,CODE_SECT_ACT,CODE_REG_FISC,STRUCTURES,ANNEE_FISCAL,DATE_DERNIERE_VG,DATE_DERNIERE_VP,DATE_DERNIERE_AVIS,...,RISQUE_IND_32,RISQUE_IND_33,RISQUE_IND_34,RATIO_IND_37,RISQUE_IND_37,RISQUE_IND_38,RISQUE_IND_39,RISQUE_IND_49,RISQUE_IND_57,RISQUE_IND_58
0,00026269T,FOLIDIA DIT JOEL TANKOANO (LYCEE PRIVE EMMAUS),ACTIF,8021.0,RN,DME/HAUTS-BASSINS,NaN,2017-04-13T00:00:00Z,2023-01-25T00:00:00Z,2023-10-11T00:00:00Z,...,vert,vert,vert,0.0,vert,vert,vert,Non disponible,Non disponible,Non disponible

In [21]:
resultat_rni[:1]

,NUM_IFU,NOM_MINEFID,ETAT,CODE_SECT_ACT,CODE_REG_FISC,STRUCTURES,ANNEE_FISCAL,DATE_DERNIERE_VG,DATE_DERNIERE_VP,DATE_DERNIERE_AVIS,...,RISQUE_IND_32,RISQUE_IND_33,RISQUE_IND_34,RISQUE_IND_37,RATIO_IND_37,RISQUE_IND_38,RISQUE_IND_39,RISQUE_IND_49,RISQUE_IND_57,RISQUE_IND_58
0,00026269T,FOLIDIA DIT JOEL TANKOANO (LYCEE PRIVE EMMAUS),ACTIF,8021.0,RN,DME/HAUTS-BASSINS,NaN,2017-04-13T00:00:00Z,2023-01-25T00:00:00Z,2023-10-11T00:00:00Z,...,vert,vert,vert,vert,0.0,vert,vert,Non disponible,Non disponible,Non disponible

In [10]:
x = [c for c in resultat_rni.columns if c not in bd_tva_shiny.columns ]

In [11]:
y = [c for c in bd_tva_shiny.columns if c not in resultat_rni.columns ]

In [12]:
x

['ANNEE']

In [13]:
y

[]

In [6]:
merged_df.columns = merged_df.columns.str.upper()

In [7]:
result_df = merged_df[BASE_COLUMNS].copy()

In [8]:
result_df.columns

Index(['NUM_IFU', 'NOM_MINEFID', 'ETAT', 'CODE_SECT_ACT', 'CODE_REG_FISC',
       'STRUCTURES', 'ANNEE_FISCAL', 'DATE_DERNIERE_VG', 'DATE_DERNIERE_VP',
       'DATE_DERNIERE_AVIS'],
      dtype='object')

In [9]:
risk_df = ControleIndicators.calculate_all_indicators(merged_df,result_df)

In [10]:
NONEL = ControleIndicators.get_liste_non_eligibles(risk_df)

In [11]:
len(NONEL)

328492

In [12]:
risk_df

,NUM_IFU,NOM_MINEFID,ETAT,CODE_SECT_ACT,CODE_REG_FISC,STRUCTURES,ANNEE_FISCAL,DATE_DERNIERE_VG,DATE_DERNIERE_VP,DATE_DERNIERE_AVIS,RISQUE_IND_15_A,RISQUE_IND_15_B,RISQUE_IND_16
0,00026339U,GILBERT KIENDREBEOGO,ACTIF,5223.0,RSI,DCI-OUAGA 1,NaN,2022-03-24T00:00:00Z,2023-08-07T00:00:00Z,2023-08-30T00:00:00Z,vert,vert,vert
1,00026269T,FOLIDIA DIT JOEL TANKOANO (LYCEE PRIVE EMMAUS),ACTIF,8021.0,RN,DME/HAUTS-BASSINS,NaN,2017-04-13T00:00:00Z,2023-01-25T00:00:00Z,2023-10-11T00:00:00Z,vert,vert,vert
2,00026274N,PINSAPO GOLD (PINSAPO GOLD SA),ACTIF,1321.0,RN,DME/CENTRE V,2022.0,2016-04-18T00:00:00Z,2024-08-08T00:00:00Z,2024-11-05T00:00:00Z,vert,vert,vert
3,00026274N,PINSAPO GOLD (PINSAPO GOLD SA),ACTIF,1321.0,RN,DME/CENTRE V,2023.0,2016-04-18T00:00:00Z,2024-08-08T00:00:00Z,2024-11-05T00:00:00Z,vert,vert,vert
4,00026274N,PINSAPO GOLD (PINSAPO GOLD SA),ACTIF,1321.0,RN,DME/CENTRE V,2024.0,2016-04-18T00:00:00Z,2024-08-08T00:00:00Z,2024-11-05T00:00:00Z,vert,vert,vert
...,...,...,...,...,...,...,...,...,...,...,...,...,...
658020,00293581V,TOUWENDSIDA SERGE BAGRE,ACTIF,9304.0,ND,NaN,NaN,2025-12-09T14:19:04Z,2025-12-09T14:19:04Z,2025-12-09T14:19:04Z,vert,vert,vert
658021,00293585M,OUSMANE SAWADOGO (ETABLISSEMENTSAWADOGO OUSMAN...,ACTIF,2022.0,CME,NaN,NaN,2025-12-09T14:39:20Z,2025-12-09T14:39:20Z,2025-12-09T14:39:20Z,vert,vert,vert
658022,00293586L,OUEDRAOGO RISSANATA (RISSANATA OUEDRAOGO),ACTIF,9304.0,ND,NaN,NaN,2025-12-09T14:41:08Z,2025-12-09T14:41:08Z,2025-12-09T14:41:08Z,vert,vert,vert
658023,00293584D,IDRISSA TALL,ACTIF,9304.0,ND,NaN,NaN,2025-12-09T14:31:26Z,2025-12-09T14:31:26Z,2025-12-09T14:31:26Z,vert,vert,vert
658024,00293589X,SAVADOGO SIBIRI (SIBIRI SAVADOGO),ACTIF,9304.0,ND,NaN,NaN,2025-12-09T14:56:42Z,2025-12-09T14:56:42Z,2025-12-09T14:56:42Z,vert,vert,vert

In [13]:
risk_df = TVAIndicators.calculate_all_indicators(merged_df,risk_df)

In [14]:
risk_df

,NUM_IFU,NOM_MINEFID,ETAT,CODE_SECT_ACT,CODE_REG_FISC,STRUCTURES,ANNEE_FISCAL,DATE_DERNIERE_VG,DATE_DERNIERE_VP,DATE_DERNIERE_AVIS,...,RISQUE_IND_10,GAP_IND_10,SCORE_IND_10,RISQUE_IND_12,GAP_IND_12,SCORE_IND_12,RISQUE_IND_13,GAP_IND_13,SCORE_IND_13,RISQUE_IND_14
0,00026339U,GILBERT KIENDREBEOGO,ACTIF,5223.0,RSI,DCI-OUAGA 1,NaN,2022-03-24T00:00:00Z,2023-08-07T00:00:00Z,2023-08-30T00:00:00Z,...,Non disponible,0.0,0,Non disponible,0.0,0,Non disponible,0.0,0,vert
1,00026269T,FOLIDIA DIT JOEL TANKOANO (LYCEE PRIVE EMMAUS),ACTIF,8021.0,RN,DME/HAUTS-BASSINS,NaN,2017-04-13T00:00:00Z,2023-01-25T00:00:00Z,2023-10-11T00:00:00Z,...,Non disponible,0.0,0,Non disponible,0.0,0,Non disponible,0.0,0,vert
2,00026274N,PINSAPO GOLD (PINSAPO GOLD SA),ACTIF,1321.0,RN,DME/CENTRE V,2022.0,2016-04-18T00:00:00Z,2024-08-08T00:00:00Z,2024-11-05T00:00:00Z,...,vert,0.0,4,Non disponible,0.0,0,Non disponible,0.0,0,rouge
3,00026274N,PINSAPO GOLD (PINSAPO GOLD SA),ACTIF,1321.0,RN,DME/CENTRE V,2023.0,2016-04-18T00:00:00Z,2024-08-08T00:00:00Z,2024-11-05T00:00:00Z,...,vert,0.0,4,vert,0.0,3,vert,0.0,3,rouge
4,00026274N,PINSAPO GOLD (PINSAPO GOLD SA),ACTIF,1321.0,RN,DME/CENTRE V,2024.0,2016-04-18T00:00:00Z,2024-08-08T00:00:00Z,2024-11-05T00:00:00Z,...,vert,0.0,4,Non disponible,0.0,0,Non disponible,0.0,0,rouge
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
658020,00293581V,TOUWENDSIDA SERGE BAGRE,ACTIF,9304.0,ND,NaN,NaN,2025-12-09T14:19:04Z,2025-12-09T14:19:04Z,2025-12-09T14:19:04Z,...,Non disponible,0.0,0,Non disponible,0.0,0,Non disponible,0.0,0,vert
658021,00293585M,OUSMANE SAWADOGO (ETABLISSEMENTSAWADOGO OUSMAN...,ACTIF,2022.0,CME,NaN,NaN,2025-12-09T14:39:20Z,2025-12-09T14:39:20Z,2025-12-09T14:39:20Z,...,Non disponible,0.0,0,Non disponible,0.0,0,Non disponible,0.0,0,vert
658022,00293586L,OUEDRAOGO RISSANATA (RISSANATA OUEDRAOGO),ACTIF,9304.0,ND,NaN,NaN,2025-12-09T14:41:08Z,2025-12-09T14:41:08Z,2025-12-09T14:41:08Z,...,Non disponible,0.0,0,Non disponible,0.0,0,Non disponible,0.0,0,vert
658023,00293584D,IDRISSA TALL,ACTIF,9304.0,ND,NaN,NaN,2025-12-09T14:31:26Z,2025-12-09T14:31:26Z,2025-12-09T14:31:26Z,...,Non disponible,0.0,0,Non disponible,0.0,0,Non disponible,0.0,0,vert
658024,00293589X,SAVADOGO SIBIRI (SIBIRI SAVADOGO),ACTIF,9304.0,ND,NaN,NaN,2025-12-09T14:56:42Z,2025-12-09T14:56:42Z,2025-12-09T14:56:42Z,...,Non disponible,0.0,0,Non disponible,0.0,0,Non disponible,0.0,0,vert

In [28]:
risk_df["RISQUE_IND_15_B"]

0         vert
1         vert
2         vert
3         vert
4         vert
          ...
658020    vert
658021    vert
658022    vert
658023    vert
658024    vert
Name: RISQUE_IND_15_B, Length: 658025, dtype: object

In [29]:
risk_df_RNI = risk_df[risk_df["CODE_REG_FISC"] == "RNI"]
risk_df_RN = risk_df[risk_df["CODE_REG_FISC"] == "RN"]
risk_df_ND = risk_df[risk_df["CODE_REG_FISC"] == "ND"]
risk_df_CME = risk_df[risk_df["CODE_REG_FISC"] == "CME"]
risk_df_CSB = risk_df[risk_df["CODE_REG_FISC"] == "CSB"]
risk_df_RSI = risk_df[risk_df["CODE_REG_FISC"] == "RSI"]

In [ ]:
EligibleBuilde = EligibleBuilder(risk_df_RN)

In [32]:
ELIGIBLE_IND_1 = EligibleBuilder.ELIGIBLE_IND1()

In [33]:
ELIGIBLE_IND_1

{'unique_NUM_IFU_count': 2543,
 'max_DATE_DERNIERE_AVIS': '2022-12-30T14:47:07Z',
 'max_DATE_DERNIERE_VG': '2022-12-30T14:47:07Z',
 'max_DATE_DERNIERE_VP': '2022-12-30T14:47:07Z',
 'unique_ANNEE_FISCAL': [2023.0, 2024.0, 2025.0]}

In [13]:
import openpyxl

In [16]:
#save it all 
risk_df_RNI.to_excel("../data/eligible/risk_indicators_RNI_122025.xlsx", index=False)
risk_df_RN.to_excel("../data/eligible/risk_indicators_RN_122025.xlsx", index=False)
risk_df_ND.to_excel("../data/eligible/risk_indicators_ND_122025.xlsx", index=False)
risk_df_CME.to_excel("../data/eligible/risk_indicators_CME_122025.xlsx", index=False)
risk_df_CSB.to_excel("../data/eligible/risk_indicators_CSB_122025.xlsx", index=False)
risk_df_RSI.to_excel("../data/eligible/risk_indicators_RSI_122025.xlsx", index=False)