In [3]:
from core.fiches_generator import FichesGenerator
import pandas as pd

In [21]:
import os
import sys
from core.data_loader import DataLoader
from db.ods import connectionOds
from core.risk_compute import RiskComputer
from data_extractor import DataExtractor 
from core import sql_ifu
from dotenv import load_dotenv
from sqlalchemy import create_engine
load_dotenv()

True

In [3]:
oracle_engine = connectionOds()
connect = oracle_engine.connect()

In [5]:
loader = DataLoader(oracle_engine)
computer = RiskComputer()
extractor = DataExtractor()

2026-04-10 16:38:52,416 - core.data_loader - INFO - Chargement des données de référence...
2026-04-10 16:38:52,552 - core.data_loader - INFO - NON_EIGIBLE.xlsx chargé: 6204 IFU exclus
2026-04-10 16:38:52,562 - core.data_loader - INFO - Entreprises_LIEES.xlsx chargé: 100 lignes
2026-04-10 16:38:52,572 - core.data_loader - INFO - ../docs/META_DONNEES.xlsx chargé
2026-04-10 16:38:52,576 - core.data_loader - INFO - ../docs/FICHE_PISTES_INVESTIGATION.xlsx chargé
2026-04-10 16:38:52,743 - core.data_loader - INFO - ../docs/NomenclatureSH.xlsx chargé
2026-04-10 16:38:52,757 - core.data_loader - INFO - ../docs/DCF_ACTIVITES.xlsx chargé
2026-04-10 16:38:52,759 - core.risk_compute - INFO - Chargement des données de référence...
2026-04-10 16:38:52,888 - core.risk_compute - INFO - NON_EIGIBLE.xlsx chargé: 6984 IFU a exclur
2026-04-10 16:38:52,897 - core.risk_compute - INFO - Entreprises_LIEES.xlsx chargé: 100 lignes

In [6]:
ifu_db_url = os.getenv("IFU_DB_URL")
ODS_DB_URL = os.getenv("ODS_DB_URL")

In [7]:
engin = create_engine(ifu_db_url).connect()

In [8]:
data_ifu = extractor.extract_data(engin, sql_ifu)

In [20]:
data_ifu.to_csv("../data/data_ifu.csv", index=False)

In [19]:
data_dgb =loader.extract_dgd(connect)
data_dgb.to_csv("../data/data_dgb.csv", index=False)

2026-04-10 17:11:35,430 - core.data_loader - INFO - Extraction DGD complète avec nomenclature
2026-04-10 17:11:45,431 - core.data_loader - INFO - DGD extraite de la base Oracle et sauvegardée: 38595 lignes
2026-04-10 17:11:45,433 - core.data_loader - INFO - DGD complète extraite: 38595 lignes en 10.00s

In [ ]:
quantume_name="Q1_2026"
risk_data_path = f"../data/risk_contribuables/{quantume_name}.csv"
quantume_path  = f"../programmes/{quantume_name}.xlsx"

In [5]:
data_ifu = pd.read_csv("../data/data_ifu.csv")
data_dgd =  pd.read_csv("../data/data_dgb.csv")

In [ ]:
quantume_df = pd.read_excel(quantume_path,skiprows=1)
risk_data = pd.read_csv(risk_data_path,sep=";")

In [ ]:
gen = FichesGenerator(quantume_name = quantume_name,
                      quantume=quantume_df,
                      ifu_data=data_ifu,
                      risk_data=risk_data,
                      data_dgd=data_dgd)

2026-04-10 19:29:50,493 - core.fiches_generator - INFO - Chargement des données de référence...
2026-04-10 19:29:50,540 - core.fiches_generator - INFO - ../docs/META_DONNEES.xlsx chargé
2026-04-10 19:29:50,565 - core.fiches_generator - INFO - ../docs/FICHE_PISTES_INVESTIGATION.xlsx chargé
2026-04-10 19:29:50,894 - core.fiches_generator - INFO - ../docs/NomenclatureSH.xlsx chargé
2026-04-10 19:29:50,927 - core.fiches_generator - INFO - ../docs/DCF_ACTIVITES.xlsx chargé
2026-04-10 19:29:50,951 - core.fiches_generator - INFO - ../docs/SUIVI.xlsx chargé

In [15]:
drut = gen.process()
drut.to_csv("../data/data_generated_fiche.csv", index=False)

In [16]:
drut.head()

,STRUCTURES_x,BRIGADES,NUM_IFU,NOM,ACTIVITES,PROGRAMME,ANNEE_ GESTION,TYPE_ CONTROLE,UNNAMED: 8,NOM_MINEFID,...,RISQUE_IND_6,GAP_IND_6,SCORE_IND_6,STRUCTURES,LATITUDE,LONGITUDE,ACTIVITES_IFU,SOUS_UR,UR,contribuables
0,DOS,UG-VSPFE,00002920Z,BANQUE ATLANTIQUE BURKINA FASO (BABF),AUTRES ACTIVITÉS MONÉTAIRES,1er QUANTUM,2023-2024-2025,VG,NaN,BANQUE ATLANTIQUE BURKINA FASO (BABF),...,Non disponible,0.0,0,DIRECTION GRANDES ENTREPRISES,12.369139,-1.0,AUTRES ACTIVITÉS MONÉTAIRES,DIRECTION_GRANDES_ENTREPRISES,DOS,00002920Z_DIRECTION_GRANDES_ENTREPRISES_UG_VSPFE
1,DOS,UG-VSPFE,00002920Z,BANQUE ATLANTIQUE BURKINA FASO (BABF),AUTRES ACTIVITÉS MONÉTAIRES,1er QUANTUM,2023-2024-2025,VG,NaN,BANQUE ATLANTIQUE BURKINA FASO (BABF),...,Non disponible,0.0,0,DIRECTION GRANDES ENTREPRISES,12.369139,-1.0,AUTRES ACTIVITÉS MONÉTAIRES,DIRECTION_GRANDES_ENTREPRISES,DOS,00002920Z_DIRECTION_GRANDES_ENTREPRISES_UG_VSPFE
2,DOS,UG-VSPFE,00002920Z,BANQUE ATLANTIQUE BURKINA FASO (BABF),AUTRES ACTIVITÉS MONÉTAIRES,1er QUANTUM,2023-2024-2025,VG,NaN,BANQUE ATLANTIQUE BURKINA FASO (BABF),...,Non disponible,0.0,0,DIRECTION GRANDES ENTREPRISES,12.369139,-1.0,AUTRES ACTIVITÉS MONÉTAIRES,DIRECTION_GRANDES_ENTREPRISES,DOS,00002920Z_DIRECTION_GRANDES_ENTREPRISES_UG_VSPFE
3,DOS,UG-VSPFE,00002920Z,BANQUE ATLANTIQUE BURKINA FASO (BABF),AUTRES ACTIVITÉS MONÉTAIRES,1er QUANTUM,2023-2024-2025,VG,NaN,BANQUE ATLANTIQUE BURKINA FASO (BABF),...,Non disponible,0.0,0,DIRECTION GRANDES ENTREPRISES,12.369139,-1.0,AUTRES ACTIVITÉS MONÉTAIRES,DIRECTION_GRANDES_ENTREPRISES,DOS,00002920Z_DIRECTION_GRANDES_ENTREPRISES_UG_VSPFE
4,DOS,UG-VSPFE,00002920Z,BANQUE ATLANTIQUE BURKINA FASO (BABF),AUTRES ACTIVITÉS MONÉTAIRES,1er QUANTUM,2023-2024-2025,VG,NaN,BANQUE ATLANTIQUE BURKINA FASO (BABF),...,Non disponible,0.0,0,DIRECTION GRANDES ENTREPRISES,12.369139,-1.0,AUTRES ACTIVITÉS MONÉTAIRES,DIRECTION_GRANDES_ENTREPRISES,DOS,00002920Z_DIRECTION_GRANDES_ENTREPRISES_UG_VSPFE

In [23]:
risk_data

,NUM_IFU,NOM_MINEFID,ETAT,CODE_SECT_ACT,CODE_REG_FISC,STRUCTURES,DATE_DERNIERE_VG,DATE_DERNIERE_VP,DATE_DERNIERE_AVIS,ANNEE,...,SCORE_IND_4,RISQUE_IND_5,GAP_IND_5,SCORE_IND_5,RISQUE_IND_7_A,RISQUE_IND_7_B,RISQUE_IND_9,RISQUE_IND_6,GAP_IND_6,SCORE_IND_6
0,00000001E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023.0,...,0,Ratio non calculable,0.0,0,Non disponible,Non disponible,Non disponible,Non disponible,0.0,0
1,00000001E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0,...,0,Ratio non calculable,0.0,0,Non disponible,Non disponible,Non disponible,Non disponible,0.0,0
2,00000001E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025.0,...,0,Ratio non calculable,0.0,0,Non disponible,Non disponible,Non disponible,Non disponible,0.0,0
3,00000001E,ZEGOMYANDE JUSTIN ROUAMBA (ETS RZF),INACTIF,5226.0,RN,DME/CENTRE III,NaN,NaN,NaN,NaN,...,0,Ratio non calculable,0.0,0,Non disponible,Non disponible,Non disponible,Non disponible,0.0,0
4,00000002H,NETCOM SA (NETCOM SA),INACTIF,7210.0,RN,DME/CENTRE III,NaN,NaN,NaN,2017.0,...,0,Ratio non calculable,0.0,0,vert,vert,Non disponible,Non disponible,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
772993,RF2583715,KONE/TIONOU ROSE,ACTIF,9304.0,ND,NaN,NaN,NaN,NaN,NaN,...,0,Ratio non calculable,0.0,0,Non disponible,Non disponible,Non disponible,Non disponible,0.0,0
772994,RF2583716,SAWADOGO SIDIKI,ACTIF,9304.0,ND,NaN,NaN,NaN,NaN,NaN,...,0,Ratio non calculable,0.0,0,Non disponible,Non disponible,Non disponible,Non disponible,0.0,0
772995,RF2583717,KAMBIRE COLLETTE,ACTIF,8511.0,ND,NaN,NaN,NaN,NaN,NaN,...,0,Ratio non calculable,0.0,0,Non disponible,Non disponible,Non disponible,Non disponible,0.0,0
772996,RF2583718,NANA DIEUDONNE,ACTIF,5246.0,ND,NaN,NaN,NaN,NaN,NaN,...,0,Ratio non calculable,0.0,0,Non disponible,Non disponible,Non disponible,Non disponible,0.0,0
772997,RF2583719,NIKIEMA BINTA,ACTIF,5246.0,ND,NaN,NaN,NaN,NaN,NaN,...,0,Ratio non calculable,0.0,0,Non disponible,Non disponible,Non disponible,Non disponible,0.0,0

In [ ]:
data = quantume_df.merge(risk_data,
                                on='NUM_IFU',
                                how='left').merge(data_ifu,
                                            on='NUM_IFU',
                                            how='inner')

In [15]:
data_ifu

,STRUCTURES,NUM_IFU,LATITUDE,LONGITUDE,ACTIVITES_IFU
0,DCI-OUAGA 6,00106806X,NaN,-1.0,COMMERCE DE DÉTAIL EN MAGASIN SPÉCIALISÉ DE PR...
1,SDI SIDERADOUGOU,00106807K,0.0,-1.0,ENSEIGNEMENT SECONDAIRE GÉNÉRAL
2,DCI-OUAGA 6,00106791H,NaN,-1.0,AUTRES COMMERCES DE GROS
3,DME/CENTRE IV,00107075G,NaN,-1.0,ACTION SOCIALE
4,DME/CENTRE IV,00107076S,NaN,-1.0,ACTION SOCIALE
...,...,...,...,...,...
303281,KOURITENGA,00298335H,0.0,0.0,AUTRES ACTIVITÉS DE SERVICES PERSONNELS
303282,DCI-OUAGA 6,00298336T,0.0,0.0,CONSTRUCTION DES BÂTIMENTS
303283,SDI N'DOROLA,00298343G,0.0,0.0,COMMERCE DE DÉTAIL EN MAGASIN NON SPÉCIALISÉ
303284,DCI-OUAGA 5,00298345D,0.0,0.0,TRAVAUX D'INSTALLATION
303285,DCI-OUAGA 4,00295236N,0.0,0.0,COMMERCE DE DÉTAIL EN MAGASIN SPÉCIALISÉ DE MA...

In [36]:
data_ifu.columns = data_ifu.columns.str.upper()

In [17]:
gen.generate()

TypeError: join() argument must be str, bytes, or os.PathLike object, not 'DataFrame'